build-trust/ockam

dynamic/common/bytes.go
dynamic/main.go
dynamic/merkle.go
dynamic/node.go
dynamic/provider.go
dynamic/signature_validation.go
dynamic/types.go
dynamic/types/canonical.go
dynamic/types/commit.go
dynamic/types/pub_key.go
dynamic/types/status.go
dynamic/types/tx.go
dynamic/types/validator.go
dynamic/validator_set.go
dynamic/verifier.go
go.mod
go.sum

1. verify validator signature on precommit is valid
2. verify 2/3 of validator voting power has signed precommit
3. verify that merkle proof is valid
4. update last_trusted.json with most recent trusted validator set
Please describe the changes in your pull request.
If this pull request resolves an already recorded bug or a feature request, be sure to link to that issue.

feat: client side signature validation

---

NOTICE

Please describe the changes in your pull request.
If this pull request resolves an already recorded bug or a feature request, be sure to link to that issue.

docs: update attribution for recently added libraries

---

README.md

Updated the overview section per discussion with Matt, and minor formatting changes.

docs: overview of README.md and minor formatting

---

implementations/c/src/ockam/vault/ATECC/src/vault.c
implementations/c/test/test_ockam.c

Please describe the changes in your pull request.
If this pull request resolves an already recorded bug or a feature request, be sure to link to that issue.

feat(implementations/c): change n to 60

---

tools/builder/debian/Dockerfile

Missed this change in the builder update

build: fix dockerfile

---

implementations/c/CMakeLists.txt
implementations/c/build.gradle
implementations/c/cmake/ockam_cc_library.cmake
implementations/c/cmake/ockam_cc_test.cmake
implementations/c/cmake/platform/raspberry-pi-mac.cmake
implementations/c/cmake/platform/raspberry-pi.cmake
implementations/c/lib/memory/stdlib.c
implementations/c/lib/transport/tests/CMakeLists.txt
implementations/c/lib/transport/tests/posix_socket/tcp/test_tcp_client.c
implementations/c/lib/transport/tests/posix_socket/tcp/test_tcp_server.c
implementations/c/lib/vault/tests/aes_gcm.c
implementations/rust/crates/ockam-vault-sys/build.rs

Populate build directory with target triples and move each target build
into the target triple to prevent cross contamination.
Move test fixtures under the test directory.

build(c): add armv8-rpi3-linux-gnueabihf cross compile

---

.github/ISSUE_TEMPLATE/bug_report.md

Updated issue template of this repository to new template format.

Update Issue Template

---

Vagrantfile
implementations/elixir/lib/transport/tcp/connection.ex

fix: build hanging in ci due to connection process not responding

---

implementations/c/include/ockam/queue.h
implementations/c/lib/queue/queue.c
implementations/c/lib/queue/tests/queue_test.c

- Added ability to grow queue
- Resolve memory free with 0 buff_size
- Resolve automatically grow on enqueue if needed

feat(c): Add growing queue functionality

---

README.md

docs: add covenant badge to readme

---

implementations/c/CMakeLists.txt

test(c): move ockam_build_tests flag definition before its usage

---

implementations/rust/Cargo.lock
implementations/rust/Cargo.toml
implementations/rust/vault/Cargo.toml

feat(rust): change to not build the other C based vault and wrap rust

---

implementations/rust/vault/Cargo.lock
implementations/rust/vault/Cargo.toml
implementations/rust/vault/include/vault.h
implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/lib.rs
implementations/rust/vault/src/software/mod.rs

This adds the first two functions across the FFI boundary and includes the .h header file.

feat(rust): add ffi layer for vault

---

implementations/rust/vault/include/vault.h
implementations/rust/vault/src/ffi/mod.rs

feat(rust): add public key get

---

.github/workflows/ci.yml
implementations/c/ockam/codec/tests/CMakeLists.txt
implementations/c/ockam/key_agreement/xx/xx_initiator.c
implementations/c/ockam/memory/stdlib/tests/CMakeLists.txt
implementations/c/ockam/queue/pthread/queue.c
implementations/c/ockam/queue/pthread/tests/CMakeLists.txt

Use static cmocka library for tests. Enable windows CI build. Fix for #237 and #265

Fix windows build

---

implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/ffi/types.rs

After a discussion with Robin, we decided to change the rust code to handle the current vault.h.

feat(rust): change to receive references

---

implementations/c/ockam/key_agreement/xx/xx_initiator.c
implementations/rust/Cargo.lock
implementations/rust/Cargo.toml
implementations/rust/common/Cargo.toml
implementations/rust/kex/Cargo.toml
implementations/rust/kex/src/lib.rs
implementations/rust/vault/src/macros.rs
implementations/rust/vault/src/software/mod.rs

Doesn't handle the exchange yet. Just does the prologue whether its for initiator or responder

Add initial ockam key exchange prologue code

---

implementations/rust/Cargo.lock
implementations/rust/common/Cargo.toml
implementations/rust/common/src/error.rs
implementations/rust/common/src/lib.rs
implementations/rust/kex/Cargo.toml
implementations/rust/kex/src/error.rs
implementations/rust/kex/src/lib.rs
implementations/rust/vault/Cargo.toml
implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/lib.rs

Add handling of message 1 from initiator to responder

feat(rust): refactor vault and add handle message1 to kex

---

implementations/rust/kex/src/lib.rs

feat(rust): add encode and decode message 3

---

implementations/rust/kex/src/lib.rs

Add `finalize` method to start using the completed handshake state.

feat(rust): add final handshake step to establish secure transport

---

implementations/rust/Cargo.lock
implementations/rust/kex/Cargo.toml
implementations/rust/kex/src/lib.rs

Finishes key exchange and passes test 1

feat(rust): add first tests for key exchange

---

implementations/rust/kex/src/lib.rs
implementations/rust/vault/src/lib.rs
implementations/rust/vault/src/software/mod.rs

Combines ECDH and HKDF-SHA256 into one method
in Vault and applied to Key Exchange

feat(rust): refactor ecdh and hkdf-sha256

---

implementations/rust/Cargo.lock
implementations/rust/Cargo.toml
implementations/rust/channel/Cargo.toml
implementations/rust/channel/src/lib.rs
implementations/rust/vault/Cargo.toml

feat(rust): initialize channel crate

---

implementations/elixir/lib/ockam/vault/software.ex
implementations/elixir/native/vault/software/nifs.c
implementations/elixir/test/ockam/vault/software_test.exs
implementations/rust/vault/include/vault.h
implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/ffi/types.rs

Add rust vault sha256 to elixir

---

implementations/rust/Cargo.lock
implementations/rust/vault/Cargo.toml
implementations/rust/vault/src/osx/mod.rs
implementations/rust/vault/src/types.rs

Implemented
Get attributes
Get public key

feat(rust): implement more osx vault methods

---

implementations/rust/message/src/message.rs
implementations/rust/vault/src/lib.rs

refactor(rust): combine onward and return routes into a single struct

---

implementations/e/applications/ockam/lib/ockam/router.ex
implementations/e/applications/ockam/lib/ockam/telemetry.ex
implementations/e/applications/ockam/mix.exs
implementations/e/applications/ockam/mix.lock

refactor(elixir): add telemetry

---

implementations/e/applications/ockam_vault_software/native/vault/software/nifs.c
implementations/rust/vault/include/vault.h
implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/ffi/types.rs

Should be reviewed&merged after #403

fix(rust): make ffi ockam_vault_secret_t an opaque handle

---

implementations/e/applications/ockam_vault_software/lib/vault_software.ex
implementations/e/applications/ockam_vault_software/native/vault/software/nifs.c
implementations/e/applications/ockam_vault_software/test/vault_software_test.exs
implementations/rust/vault/include/vault.h
implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/ffi/types.rs

Should be reviewed&merged after #404 (if you can find it, he-he)

Add more functions to rust <-> elixir ffi

---

implementations/rust/channel/src/error.rs
implementations/rust/channel/src/lib.rs
implementations/rust/kex/src/error.rs

Let me know your thoughts on this one. This is where the channel wraps the IO

feat(rust): first method on channels

---

implementations/rust/Cargo.lock
implementations/rust/vault/Cargo.toml
implementations/rust/vault/src/software/mod.rs

bump p256 to 0.5. Similar to #445 but this fixes breaking changes.

chore(rust): update p256 to 0.5

---

implementations/rust/Cargo.lock
implementations/rust/channel/Cargo.toml
implementations/rust/channel/src/error.rs
implementations/rust/channel/src/lib.rs
implementations/rust/kex/src/lib.rs
implementations/rust/kex/src/xx.rs
implementations/rust/message/src/lib.rs
implementations/rust/router/src/lib.rs
implementations/rust/vault/src/software/mod.rs

First implementation of channels.
Doesn't handle key rotation yet but will in a future PR.

Finished first draft for channels

---

implementations/rust/channel/src/lib.rs

@robinbudd correctly pointed out that I forgot to handle xx key exchange message 2. This corrects that.

feat(rust): handle xx key agreement message 2

---

implementations/rust/channel/src/lib.rs
implementations/rust/kex/src/lib.rs
implementations/rust/kex/src/xx.rs

This reverts commit 4dd3feea822dbe9889ba9391774771ca3597e1be.

fix(rust): undo last commit

---

implementations/rust/Cargo.lock
implementations/rust/Cargo.toml
implementations/rust/channel/src/error.rs
implementations/rust/daemon/src/cli.rs
implementations/rust/daemon/src/vault.rs
implementations/rust/kex/Cargo.toml
implementations/rust/kex/src/error.rs
implementations/rust/kex/src/lib.rs
implementations/rust/kex/src/x3dh.rs
implementations/rust/kex/src/xx.rs
implementations/rust/transport/src/lib.rs
implementations/rust/vault/Cargo.toml
implementations/rust/vault/src/error.rs
implementations/rust/vault/src/lib.rs
implementations/rust/vault/src/software/mod.rs
implementations/rust/vault/src/types.rs
implementations/rust/xeddsa/Cargo.toml
implementations/rust/xeddsa/src/lib.rs

Implement the X3dh key agreement along with XEdDSA.

feat(rust): Implement X3dh key agreement

---

implementations/elixir/ockam/ockam/mix.exs
implementations/elixir/ockam/ockam_node_web/mix.exs
implementations/elixir/ockam/ockam_transport_udp/mix.exs
implementations/elixir/ockam/ockam_vault_software/mix.exs
implementations/elixir/ockam/ockam_vault_software/native/vault/key_exchange/CMakeLists.txt
implementations/elixir/ockam/ockam_vault_software/native/vault/software/CMakeLists.txt

- build(elixir): improve mix aliases in ockam app
- build(elixir): improve mix aliases in ockam_node_web app
- build(elixir): improve mix aliases in ockam_transport_udp app
- build(elixir): improve mix aliases in ockam_vault_software app
- fix(elixir): broken path of header files in ockam_vault_software
- build(elixir): use test env in test.cover mix task of ockam_vault_software

elixir build fixes and improvements

---

implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/lib.rs

feat(rust): fix vault ffi hkdf

---

.github/workflows/ci.yml
.github/workflows/nightly_builds.yml
implementations/elixir/README.md
implementations/elixir/build.gradle
implementations/elixir/ockam/ockam/lib/ockam/pipeline.ex
implementations/elixir/ockam/ockam/lib/ockam/wire.ex
implementations/elixir/ockam/ockam/lib/ockam/wire/error.ex
implementations/elixir/ockam/ockam/test/ockam/router/address_test.exs
implementations/elixir/ockam/ockam/test/ockam/telemetry_test.exs
implementations/elixir/ockam/ockam/test/ockam_test.exs
implementations/elixir/ockam/ockam_node_web/lib/node_web/socket.ex
implementations/elixir/ockam/ockam_transport_udp/lib/udp/server.ex
implementations/elixir/ockam/ockam_transport_udp/mix.lock
implementations/elixir/settings.gradle

- build(elixir): update mix.lock in ockam_transport_udp
- style(elixir): fix credo warnings
- build(elixir): make gradle build all elixir apps
- fix(elixir): broken tests in ockam app
- fix(elixir): broken test in ockam_transport_udp
- build(elixir): disable ockam_vault_software in gradle build
- docs(elixir): disable module docs for node web socket
- build(elixir): ensure gradle lint, build and test run after deps_get
- ci: setup elixir and update pinned actions

elixir build improvements

---

implementations/rust/daemon/README.md
implementations/rust/daemon/src/bin/ockamd.rs
implementations/rust/daemon/src/cli.rs
implementations/rust/daemon/src/config.rs
implementations/rust/daemon/src/initiator.rs
implementations/rust/daemon/src/lib.rs
implementations/rust/daemon/src/node.rs
implementations/rust/daemon/src/responder.rs
implementations/rust/daemon/src/vault.rs
implementations/rust/daemon/src/worker.rs
implementations/rust/transport/src/lib.rs

This PR (once merged) should make for a nicer place off `develop` for @robinbudd to rebase from and apply her recent changes.

incorporate modified lib code into ockamd

---

implementations/rust/daemon/src/lib.rs
implementations/rust/daemon/src/node.rs
implementations/rust/daemon/src/vault.rs
implementations/rust/node/src/node.rs
implementations/rust/system/src/commands.rs
implementations/rust/vault/src/file/mod.rs
implementations/rust/vault/src/lib.rs

Restricts writes to disk for keys that are of type persistent.

fix(rust): only save key to disk if type is persistent

---

implementations/rust/daemon/src/cli.rs
implementations/rust/daemon/src/config.rs
implementations/rust/daemon/src/node.rs

- feat(rust): use .key suffix for vault secrets on disk, pub identity-name
- feat(rust): re-use key based on identity name provided in cli

feat(rust): re-use key based on identity name provided in cli

---

implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/ffi/types.rs
implementations/rust/vault/src/lib.rs

This exposes the filesystem vault over ffi

feat(rust): add filesystem ffi

---

README.md

add staging (re-written to live urls) links to README

docs: update readme with links

---

implementations/c/CMakeLists.txt
implementations/elixir/ockam/ockam/mix.exs
implementations/elixir/ockam/ockam_hub/mix.exs
implementations/elixir/ockam/ockam_node_web/mix.exs
implementations/elixir/ockam/ockam_vault_software/mix.exs
implementations/elixir/ockam/ockam_vault_software/native/CMakeLists.txt

- feat(c): bump version to 0.10.0
- feat(elixir): bump version to 0.10.0

bump versions

---

documentation/concepts/enrollment.md
documentation/concepts/enterprise-systems.md
documentation/concepts/vaults.md

content: concept docs order and titles

---

implementations/rust/channel/src/lib.rs
implementations/rust/daemon/src/node.rs
implementations/rust/kex/src/x3dh.rs
implementations/rust/kex/src/xx.rs
implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/file/mod.rs
implementations/rust/vault/src/software/mod.rs
implementations/rust/vault/src/types.rs

chore(rust): make secretkey and publickey more usable

---

implementations/elixir/ockam/ockam_vault_software/lib/vault_software.ex
implementations/elixir/ockam/ockam_vault_software/native/vault/software/nifs.c
implementations/elixir/ockam/ockam_vault_software/test/vault_software_test.exs
implementations/rust/channel/src/lib.rs
implementations/rust/daemon/src/node.rs
implementations/rust/kex/src/lib.rs
implementations/rust/kex/src/x3dh.rs
implementations/rust/kex/src/xx.rs
implementations/rust/node/src/node.rs
implementations/rust/vault/include/vault.h
implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/file/mod.rs
implementations/rust/vault/src/lib.rs
implementations/rust/vault/src/software/mod.rs

Split Vault trait

---

implementations/rust/examples/Cargo.toml
implementations/rust/examples/examples/worker.rs
implementations/rust/ockam/src/lib.rs
implementations/rust/ockam/src/message.rs
implementations/rust/ockam/src/node.rs
implementations/rust/ockam/src/queue.rs
implementations/rust/ockam/src/route.rs
implementations/rust/ockam/src/worker.rs

First worker example and its dependencies.
Brings in the core structs and traits for Message, WorkerBuilder, etc.

feat(rust): worker example

---

implementations/rust/ockam/ockam/src/address.rs
implementations/rust/ockam/ockam/src/message.rs
implementations/rust/ockam/ockam/src/node.rs
implementations/rust/ockam/ockam/src/route.rs
implementations/rust/ockam/ockam/src/worker.rs

chore(rust): fix clippy concerns

---

implementations/rust/.gitignore
implementations/rust/examples/workers/examples/worker_send.rs
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam/src/lib.rs
implementations/rust/ockam/ockam/src/queue.rs
implementations/rust/ockam/ockam/src/worker.rs
implementations/rust/ockam/ockam_error/Cargo.toml
implementations/rust/ockam/ockam_error/src/lib.rs

feat(rust): add ockam_error

---

implementations/rust/examples/node/Cargo.lock
implementations/rust/examples/worker/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_node_attribute/Cargo.lock
implementations/rust/ockam/ockam_node_attribute/Cargo.toml
implementations/rust/ockam/ockam_node_attribute/README.md

1. Fix readme
2. Bump patch version

ockam_node_attribute v0.1.1

---

implementations/rust/examples/node/Cargo.lock
implementations/rust/examples/worker/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_node_attribute/CHANGELOG.md
implementations/rust/ockam/ockam_node_attribute/Cargo.lock
implementations/rust/ockam/ockam_node_attribute/Cargo.toml
implementations/rust/ockam/ockam_node_attribute/README.md

ockam_node_attribute v0.1.2

---

implementations/elixir/ockam/ockam/lib/ockam/node.ex
implementations/elixir/ockam/ockam/lib/ockam/serializable.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/udp/address.ex
implementations/elixir/ockam/ockam/test/ockam/transport/udp/address_test.exs

- fix(elixir): serialized address deserializes back to original value
- feat(elixir): handle incoming routed messages in node

fix routing

---

implementations/rust/ockam/ockam_core/CHANGELOG.md
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_core/README.md

*  ockam_core crate 0.2.0
Version bump to 0.2.0 in preparation for release.

feat(rust): ockam_core crate 0.2.0

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_node/CHANGELOG.md
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/README.md

feat(rust): ockam_node crate v0.1.0

---

implementations/rust/ockam/ockam_node/Cargo.toml

feat(rust): ockam crate v0.1.0

---

implementations/rust/ockam/ockam_node/CHANGELOG.md

Found an accidental duplicate section in Changelog

chore(rust): additional changelog fixes

---

implementations/rust/ockam/ockam_node/CHANGELOG.md
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/README.md

Added meta-info documentation.

Release ockam_node v0.1.1

---

implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/README.md

Release for Toml fixes for crates.io

feat(rust): ockam_node crate v0.1.2

---

implementations/rust/ockam/ockam/CHANGELOG.md
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam/README.md

Adds description to toml. Release ockam crate v0.1.0

ockam crate v0.1.0

---

documentation/architecture/decisions/0002-profile-event-signing.md

feat(content): adr for profile event keys

---

documentation/architecture/decisions/0003-runbooks-and-checklists.md

Proposed ADR: Checklists and Runbooks

docs: adr for checklists and runbooks

---

implementations/rust/examples/node/examples/create_node_with_macro.rs
implementations/rust/examples/node/examples/create_node_without_macro.rs
implementations/rust/examples/node/examples/create_ping_pong_node.rs
implementations/rust/examples/worker/examples/create_worker.rs
implementations/rust/ockam/ockam/tests/node_attribute/can_be_used_on_main.rs
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_core/src/address.rs
implementations/rust/ockam/ockam_core/src/worker.rs
implementations/rust/ockam/ockam_node/src/executor.rs
implementations/rust/ockam/ockam_node/src/node.rs
implementations/rust/ockam/ockam_node/src/relay.rs

A set of changes to simplify and document usage of ockam workers

chore(rust): ockam worker cleanup and examples

---

implementations/rust/ockam/ockam_credential/CHANGELOG.md
implementations/rust/ockam/ockam_credential/Cargo.lock
implementations/rust/ockam/ockam_credential/Cargo.toml

Release ockam_credential crate v0.2.0

feat(rust): ockam_credential crate v0.2.0

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_node/CHANGELOG.md
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/README.md
implementations/rust/ockam/ockam_node/src/executor.rs
implementations/rust/ockam/ockam_node/src/node.rs

- Message trait implementation.
- Messages for starting and stopping Workers.
- Changed internal registry implementation.
- Previous Message implementation (NodeMessage)
- Relay abstraction prototype

ockam_node crate v0.2.0

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_node/CHANGELOG.md
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/README.md
implementations/rust/ockam/ockam_node/src/executor.rs
implementations/rust/ockam/ockam_node/src/node.rs

- Message trait implementation.
- Messages for starting and stopping Workers.
- Changed internal registry implementation.
- Previous Message implementation (NodeMessage)
- Relay abstraction prototype

feat(rust): ockam_node crate v0.2.0

---

implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/CHANGELOG.md
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml
implementations/rust/ockam/ockam_vault_core/README.md

- Symmetric and Asymmetric Vault traits.
- Secret Attributes.

feat(rust) ockam_vault_core crate v0.2.0

---

implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_vault/CHANGELOG.md
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault/README.md

- Symmetric and Asymmetric SoftwareVault implementations.
- Fixes to error propagation and entity construction.

feat(rust): ockam_vault crate v0.2.0

---

implementations/rust/ockam/ockam_vault/Cargo.toml
tools/docker/README.md

Rebasing for ockam_vault release with keyword fix

Release ockam_vault v0.2.0

---

implementations/rust/ockam/ockam/CHANGELOG.md
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam/README.md

- Contact and Profile APIs.
- Profile Changes API.
- Improved error handling.

feat(rust): ockam crate v0.2.0

---

implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx.ex
implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/initiator.ex
implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/protocol.ex
implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/responder.ex
implementations/elixir/ockam/ockam/lib/ockam/vault.ex
implementations/elixir/ockam/ockam/mix.exs
implementations/elixir/ockam/ockam/test/ockam/secure_channel/key_establishment_protocol/xx/protocol_test.exs
implementations/rust/examples/node/Cargo.lock
implementations/rust/examples/worker/Cargo.lock

- build(rust): update node examples cargo lock
- build(rust): update worker examples cargo lock
- feat(elixir): add ockam_vault_software to ockam
- feat(elixir): add vault api module
- feat(elixir): add xx key establishment protocol

vault and key exchange

---

implementations/rust/examples/worker/examples/worker_stateful.rs
implementations/rust/ockam/ockam_node/src/executor.rs
implementations/rust/ockam/ockam_node/src/mailbox.rs
implementations/rust/ockam/ockam_node_attribute/src/lib.rs

Rebase of https://github.com/ockam-network/ockam/pull/920

Rebase ockam worker ergonomics

---

.github/dependabot.yml
.github/workflows/ci.yml
implementations/elixir/build.gradle

- ci: add rust crates to dependabot workflow
- ci: breakdown build into smaller parallel jobs

ci parallel

---

implementations/rust/examples/credentials/src/main.rs
implementations/rust/ockam/ockam/src/credential.rs
implementations/rust/ockam/ockam/src/credential/holder.rs
implementations/rust/ockam/ockam/src/credential/issuer.rs
implementations/rust/ockam/ockam/src/credential/verifier.rs

Rebase of https://github.com/ockam-network/ockam/pull/972

feat(rust): prefix terms with credential

---

implementations/rust/examples/node/examples/create_ping_pong_node.rs
implementations/rust/examples/worker/examples/worker_initialize.rs
implementations/rust/examples/worker/examples/worker_send_message.rs
implementations/rust/ockam/ockam_core/src/worker.rs
implementations/rust/ockam/ockam_node/src/relay.rs

chore(rust): change worker initialize to be async

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_node_attribute/CHANGELOG.md
implementations/rust/ockam/ockam_node_attribute/Cargo.lock
implementations/rust/ockam/ockam_node_attribute/Cargo.toml

- Increased validation of macro parameters.
- Documentation edits.

feat(rust): ockam_node_attribute crate v0.1.4

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_router/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/CHANGELOG.md
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml
implementations/rust/ockam/ockam_vault_core/README.md

- Traits renamed for consistency.
- Documentation edits.

feat(rust): ockam_vault_core crate v0.2.1

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_router/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_vault/CHANGELOG.md
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/CHANGELOG.md
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml
implementations/rust/ockam/ockam_vault_core/README.md

- Traits renamed for consistency.
- Documentation edits.

feat(rust): ockam_vault crate v0.2.1 

---

implementations/rust/ockam/ockam_ffi/CHANGELOG.md
implementations/rust/ockam/ockam_ffi/src/error.rs
implementations/rust/ockam/ockam_ffi/src/lib.rs

feat(rust): ockam_ffi crate v0.1.0

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/CHANGELOG.md
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml
implementations/rust/ockam/ockam_vault_core/README.md

Changing version from a patch bump to minor bump

fix(rust): bump ockam_vault_core and ockam_vault to v0.3.0

---

implementations/rust/examples/worker/examples/worker_multi_address.rs
implementations/rust/ockam/ockam_core/src/address.rs
implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/executor.rs
implementations/rust/ockam/ockam_node/src/mailbox.rs
implementations/rust/ockam/ockam_node/src/messages.rs
implementations/rust/ockam/ockam_node/src/node.rs
implementations/rust/ockam/ockam_node/src/relay.rs

Rebasing https://github.com/ockam-network/ockam/pull/991

feat(rust): support multiple addresses per worker

---

implementations/rust/build.gradle
implementations/rust/examples/node/Cargo.lock
implementations/rust/examples/tcp/Cargo.lock
implementations/rust/examples/worker/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_router/Cargo.lock

Adds missing/new crates to `build.gradle`

fix(rust): add missing crates to gradle checks

---

implementations/rust/examples/credentials/Cargo.lock
implementations/rust/examples/credentials/Cargo.toml
implementations/rust/examples/credentials/src/holder.rs
implementations/rust/examples/credentials/src/issuer.rs
implementations/rust/examples/credentials/src/util.rs
implementations/rust/examples/credentials/src/verifier.rs
implementations/rust/ockam/ockam/src/credential/issuer.rs

Rebase https://github.com/ockam-network/ockam/pull/1001

 feat(rust): additional cli args for issuer

---

implementations/rust/examples/node/Cargo.lock
implementations/rust/examples/worker/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_core/CHANGELOG.md
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_core/README.md
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_router/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml

- Support multiple addresses per worker.

feat(rust): ockam_core v0.5.0

---

implementations/rust/build.gradle
implementations/rust/examples/tcp/Cargo.lock
implementations/rust/ockam/ockam/CHANGELOG.md
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam/README.md
implementations/rust/ockam/ockam_examples/examples/credentials.rs
implementations/rust/ockam/ockam_examples/src/util.rs
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_router/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock

- Lease API.
- Credential API.
- Profile authentication.
- Profile key rotation.
- Contact and Profile APIs file locations have been reorganized.
- Use new trait names from `ockam_vault_core`.
- Dependency updates.
- Renamed `authentication_factor` to `authentication_proof`.
- Minor Profile API improvements.
- Removed explicit `async_trait` user dependency.
- Contacts has been removed in favor of profiles.

ockam v0.3.0

---

implementations/rust/ockam/ockam_vault/README.md

docs: fix ockam_vault readme

---

implementations/rust/examples/node/Cargo.lock
implementations/rust/examples/tcp/Cargo.lock
implementations/rust/examples/worker/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam/src/lib.rs
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_core/src/lib.rs
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.toml
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_router/Cargo.lock
implementations/rust/ockam/ockam_router/Cargo.toml
implementations/rust/ockam/ockam_router/src/local_router.rs
implementations/rust/ockam/ockam_router/src/router.rs
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/src/connection.rs
implementations/rust/ockam/ockam_transport_tcp/src/listener.rs
implementations/rust/ockam/ockam_transport_tcp/src/tcp_router.rs
implementations/rust/ockam/ockam_transport_tcp/src/traits.rs

Update and centralize async_trait

chore: upgrade and move async_trait dep to ockam_core

---

implementations/rust/ockam/ockam_node_attribute/Cargo.lock
implementations/rust/ockam/ockam_node_attribute/Cargo.toml

chore: upgrade syn, track minor vers

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml

Bump vault and vault core to 0.3.1

feat(rust): bump vault vers for ockam crate

---

implementations/rust/ockam/ockam_transport_tcp/CHANGELOG.md
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml

Bumping deps in prep for ockam_transport_tcp 0.2.0 release

feat(rust): update deps for ockam_transport_tcp

---

implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.toml

Adding more toml fields for crates.io

fix: additional fields for example toml

---

documentation/guides/rust/README.md
documentation/guides/rust/getting-started.md
documentation/guides/rust/step-1.md
documentation/guides/rust/step-2.md
documentation/guides/rust/step-3.md
documentation/guides/rust/step-4.md

Copy for setup and all 4 Steps

Rust Guide - Step by Step

---

documentation/guides/rust/02-transports/README.md
documentation/guides/rust/04-forwarding/README.md
documentation/guides/rust/get-started/README.md
implementations/rust/ockam/ockam_examples/examples/step-4-server.rs

Various edits and feedback incorporated

docs: rust guide edits

---

implementations/elixir/ockam/ockam_hub/lib/hub/telemetry_forwarder.ex

Rebase https://github.com/ockam-network/ockam/pull/1158

feat(elixir): helper module to send telemetry to a remote node

---

implementations/elixir/ockam/ockam_hub/config/releases.exs
implementations/elixir/ockam/ockam_hub/config/runtime.exs
implementations/elixir/ockam/ockam_hub/lib/hub.ex
implementations/elixir/ockam/ockam_hub/lib/hub/telemetry_forwarder.ex
implementations/elixir/ockam/ockam_hub/mix.exs
tools/azure/hub/azure.json
tools/azure/hub/parameters.json

This attaches telemetry to our UI so that users can see the messages they send on  their node.

feat: send messages to UI to aid end-user development

---

implementations/elixir/ockam/ockam_hub/lib/hub/telemetry_forwarder.ex
tools/azure/hub/azure.json

This is a change to make messages send correctly to the hub UI.

build: update deployment configuration and secret handling

---

implementations/rust/ockam/ockam_signature_bbs/CHANGELOG.md
implementations/rust/ockam/ockam_signature_bbs/Cargo.toml

Updated `bbs` to `ockam_signature_bbs`

fix(rust): rename bbs crate

---

implementations/rust/ockam/ockam_channel/CHANGELOG.md
implementations/rust/ockam/ockam_channel/Cargo.toml
implementations/rust/ockam/ockam_channel/src/error.rs
implementations/rust/ockam/ockam_channel/src/lib.rs
implementations/rust/ockam/ockam_channel/src/secure_channel.rs
implementations/rust/ockam/ockam_channel/src/secure_channel_listener.rs
implementations/rust/ockam/ockam_key_exchange_core/CHANGELOG.md
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/src/lib.rs
implementations/rust/ockam/ockam_key_exchange_xx/CHANGELOG.md
implementations/rust/ockam/ockam_key_exchange_xx/src/error.rs
implementations/rust/ockam/ockam_key_exchange_xx/src/lib.rs

Releasing:
1. ockam_key_exchange_core
2. ockam_key_exchange_xx
3. ockam_channel

release key exchange and channel crates

---

implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/CHANGELOG.md
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/README.md
implementations/rust/ockam/ockam_key_exchange_x3dh/CHANGELOG.md
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/CHANGELOG.md
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/README.md
implementations/rust/ockam/ockam_vault/CHANGELOG.md
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault/README.md
implementations/rust/ockam/ockam_vault_core/CHANGELOG.md
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml
implementations/rust/ockam/ockam_vault_core/README.md

Updates key exchange and vault crates to track major of internal deps

feat(rust): update ockam_core dependants

---

implementations/rust/ockam/signature_bbs_plus/CHANGELOG.md
implementations/rust/ockam/signature_bbs_plus/Cargo.toml
implementations/rust/ockam/signature_bbs_plus/README.md

Fixes typo in description field

fix: fix typo in bbs description

---

implementations/rust/ockam/ockam/CHANGELOG.md
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
tools/docker/builder/Dockerfile

Updates ockam vers to pick up ockam_core changes

fix: update ockam crate patch version

---

implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_channel/Cargo.toml
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_examples/example_projects/channel/Cargo.toml
implementations/rust/ockam/ockam_examples/example_projects/node/Cargo.toml
implementations/rust/ockam/ockam_examples/example_projects/tcp/Cargo.toml
implementations/rust/ockam/ockam_examples/example_projects/worker/Cargo.toml
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/Cargo.toml
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
tools/scripts/comby/crate-version-pin.pl
tools/scripts/comby/format-cargo-toml.toml
tools/scripts/crate-versions.sh

- Pin internal ockam crate dependencies.
- Reformat Cargo TOML.
- Add scripts to help manage version consistency.

pin cargo versions

---

implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/error.rs
implementations/rust/ockam/ockam_node/src/messages.rs
implementations/rust/ockam/ockam_node/src/router.rs

Rebase of https://github.com/ockam-network/ockam/pull/1181

feat(rust): reject to spawn worker with colliding addresses

---

implementations/rust/ockam/ockam_examples/example_projects/channel/src/bin/client.rs
implementations/rust/ockam/ockam_examples/example_projects/channel/src/bin/server.rs
implementations/rust/ockam/ockam_examples/example_projects/credentials/src/holder.rs
implementations/rust/ockam/ockam_examples/example_projects/credentials/src/verifier.rs
implementations/rust/ockam/ockam_examples/example_projects/tcp/examples/network_echo_client.rs
implementations/rust/ockam/ockam_examples/example_projects/tcp/examples/network_echo_server.rs
implementations/rust/ockam/ockam_examples/example_projects/tcp/examples/relay_echo_client.rs
implementations/rust/ockam/ockam_examples/example_projects/tcp/examples/relay_echo_server.rs
implementations/rust/ockam/ockam_transport_tcp/src/init.rs
implementations/rust/ockam/ockam_transport_tcp/src/lib.rs
implementations/rust/ockam/ockam_transport_tcp/src/router.rs

Rebase of https://github.com/ockam-network/ockam/pull/1184

feat(rust): simplify tcp worker api for most common usecase

---

implementations/rust/ockam/signature_bbs_plus/CHANGELOG.md
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.toml
implementations/rust/ockam/signature_bbs_plus/README.md
implementations/rust/ockam/signature_bbs_plus/examples/readme-source.rs

1. Fixes crate meta info, badges and links.
2. Adds example API usage in the README.
3. Adds an example source file with the same code as snippets.

docs: BBS+ README example

---

implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_examples/example_projects/worker/Cargo.toml
implementations/rust/ockam/ockam_examples/example_projects/worker/examples/worker_custom_context.rs
implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/lib.rs
implementations/rust/ockam/ockam_node/src/node.rs

Rebase of https://github.com/ockam-network/ockam/pull/1209

https://github.com/ockam-network/ockam/pull/1209

---

implementations/rust/ockam/ockam/src/lib.rs
implementations/rust/ockam/ockam_core/src/message.rs
implementations/rust/ockam/ockam_examples/example_projects/worker/examples/worker_no_peeling.rs

Rebase https://github.com/ockam-network/ockam/pull/1217

chore(rust): rename passthrough message type to any

---

documentation/architecture/decisions/0005-routing-data-formats.md

Rebase https://github.com/ockam-network/ockam/pull/1112

docs: add adr for routing protocol formats

---

implementations/rust/ockam/ockam_examples/example_projects/channel/Cargo.toml
implementations/rust/ockam/ockam_examples/example_projects/channel/src/bin/client.rs
implementations/rust/ockam/ockam_examples/example_projects/channel/src/bin/server.rs
implementations/rust/ockam/ockam_examples/example_projects/credentials/src/holder.rs
implementations/rust/ockam/ockam_examples/example_projects/credentials/src/lib.rs
implementations/rust/ockam/ockam_examples/example_projects/credentials/src/verifier.rs
implementations/rust/ockam/ockam_examples/example_projects/node/Cargo.toml
implementations/rust/ockam/ockam_examples/example_projects/tcp/Cargo.toml
implementations/rust/ockam/ockam_examples/example_projects/tcp/examples/network_echo_client.rs
implementations/rust/ockam/ockam_examples/example_projects/tcp/examples/network_echo_server.rs
implementations/rust/ockam/ockam_examples/example_projects/tcp/examples/relay_echo_client.rs
implementations/rust/ockam/ockam_examples/example_projects/tcp/examples/relay_echo_server.rs
implementations/rust/ockam/ockam_examples/example_projects/worker/Cargo.toml
implementations/rust/ockam/ockam_examples/examples/step-2-client.rs
implementations/rust/ockam/ockam_examples/examples/step-3.rs
implementations/rust/ockam/ockam_examples/examples/step-4-client.rs
implementations/rust/ockam/ockam_examples/examples/step-5-client.rs
implementations/rust/ockam/ockam_transport_tcp/src/error.rs
implementations/rust/ockam/ockam_transport_tcp/src/lib.rs

Improve the ockam_transport_tcp API to take a string for addresses

---

documentation/architecture/decisions/0006-publishing-rust-crates.md

fix: resolve adr number collision

---

implementations/rust/ockam/ockam_vault/src/symmetric_impl.rs

Fixes a condition which caused spurious assertion failures in CI

fix(rust): fix flakey encryption test

---

implementations/rust/build.gradle

Rebase of https://github.com/ockam-network/ockam/pull/1238

chore(rust): ensure cargo lock file is up to date

---

implementations/rust/ockam/ockam_node/src/context.rs

Rebase of https://github.com/ockam-network/ockam/pull/1271

fix(rust): fix return route while sending message

---

implementations/rust/ockam/ockam_examples/examples/step-4-server.rs

Fixes a regression in old website step 4

fix(rust): fix step-4-server after remotemailbox rename

---

implementations/elixir/ockam/ockam_hub/lib/hub.ex
implementations/elixir/ockam/ockam_hub/lib/hub/telemetry_forwarder.ex

To not fail on startup if UI returns unexpected HTTP code.

fix(elixir): handle all http responses from UI in telemetry forwarder

---

implementations/elixir/ockam/ockam/.credo.exs
implementations/elixir/ockam/ockam/config/config.exs
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/consumer_worker.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/publisher_proxy.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/stream.ex
implementations/elixir/ockam/ockam/lib/ockam/node.ex
implementations/elixir/ockam/ockam/lib/ockam/protocol/binary.ex
implementations/elixir/ockam/ockam/lib/ockam/protocol/message_protocol.ex
implementations/elixir/ockam/ockam/lib/ockam/protocol/protocol.ex
implementations/elixir/ockam/ockam/lib/ockam/protocol/stream.ex
implementations/elixir/ockam/ockam/lib/ockam/worker.ex
implementations/elixir/ockam/ockam_hub/lib/hub.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/stream/index.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/stream/storage.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/stream/storage/internal.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/stream/stream.ex

Stream (mailbox) service

---

documentation/guides/rust/README.md
documentation/guides/rust/get-started/00-setup/README.md
documentation/guides/rust/get-started/01-node/README.md
documentation/guides/rust/get-started/02-worker/README.md
documentation/guides/rust/get-started/05-secure-channel/README.md

Updates per Issue #1309.
Signed-off-by: Jeff Scheel <jjscheel68@gmail.com>

docs:(rust): minor updates to getting started guide

---

implementations/rust/ockam/signature_bbs_plus/GUIDE.md

docs: bbs+ guide editing

---

examples/rust/get_started/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/CHANGELOG.md
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.toml
implementations/rust/ockam/signature_bbs_plus/README.md

Corrects repository location for `signature_bbs_plus`

feat(rust): signature_bbs_plus v0.3.2

---

implementations/rust/ockam/ockam/src/profile.rs
implementations/rust/ockam/ockam/src/profile/authentication.rs
implementations/rust/ockam/ockam/src/profile/change/ctype/create_key.rs
implementations/rust/ockam/ockam/src/profile/change/ctype/rotate_key.rs
implementations/rust/ockam/ockam/src/profile/channel.rs
implementations/rust/ockam/ockam/src/profile/channel/listener.rs
implementations/rust/ockam/ockam/src/profile/contact.rs

@SanjoDeundiak what do you think about something like this?

feat(rust): initial profile traits

---

documentation/architecture/workers/README.md

First pass of worker architecture docs

docs: worker architecture

---

implementations/elixir/ockam/ockam_hub/config/runtime.exs
implementations/elixir/ockam/ockam_hub/lib/hub/service/token_lease_manager.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/token_lease_manager/cloud_service.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/token_lease_manager/cloud_service/influxdb_cloud_service.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/token_lease_manager/lease.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/token_lease_manager/storage_service.ex
implementations/elixir/ockam/ockam_hub/mix.exs
implementations/elixir/ockam/ockam_hub/mix.lock

Moved from #1322 
The original PR was breaking the build.

feat(elixir): Token Lease Manager Prototype

---

implementations/elixir/ockam/ockam/lib/ockam/secure_channel.ex
implementations/elixir/ockam/ockam/lib/ockam/secure_channel/channel.ex
implementations/elixir/ockam/ockam/lib/ockam/secure_channel/encrypted_transport_protocol/aead_aes_gcm.ex
implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/initiator.ex
implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/protocol.ex
implementations/elixir/ockam/ockam/lib/ockam/secure_channel/key_establishment_protocol/xx/responder.ex
implementations/elixir/ockam/ockam/lib/ockam/vault.ex
implementations/elixir/ockam/ockam/test/ockam/secure_channel/key_establishment_protocol/xx/protocol_test.exs
implementations/elixir/ockam/ockam/test/ockam/secure_channel_test.exs

1. add established? function to channel api
2. add encrypted transport protocol
3. add default vault secret attributes
4. add tests for secure channel

feat(elixir): improve secure channel

---

implementations/elixir/ockam/ockam_hub/config/runtime.exs
implementations/elixir/ockam/ockam_hub/lib/hub/telemetry_forwarder.ex
tools/azure/hub/azure.json

Rework of https://github.com/ockam-network/ockam/pull/1243 to only address the FQDN issue

Use env var for node address. Rework

---

examples/rust/get_started/examples/05-secure-channel.rs
examples/rust/get_started/examples/06-secure-channel-many-hops.rs
examples/rust/get_started/examples/09-secure-channel-over-many-transport-hops-initiator.rs
examples/rust/get_started/examples/09-secure-channel-over-many-transport-hops-responder.rs
examples/rust/get_started/examples/11-forwarding-via-a-cloud-node-responder.rs
examples/rust/get_started/examples/12-secure-channel-over-cloud-node-forwarding-initiator.rs
examples/rust/get_started/examples/12-secure-channel-over-cloud-node-forwarding-responder.rs
implementations/rust/ockam/ockam/src/entity/local.rs
implementations/rust/ockam/ockam_entity/src/channel.rs
implementations/rust/ockam/ockam_entity/src/channel/initiator.rs
implementations/rust/ockam/ockam_entity/src/channel/listener.rs
implementations/rust/ockam/ockam_entity/src/channel/responder.rs
implementations/rust/ockam/ockam_entity/src/channel/trust_policy.rs
implementations/rust/ockam/ockam_entity/src/channel/trust_policy/all_trust_policy.rs
implementations/rust/ockam/ockam_entity/src/channel/trust_policy/any_trust_policy.rs
implementations/rust/ockam/ockam_entity/src/channel/trust_policy/identifier_trust_policy.rs
implementations/rust/ockam/ockam_entity/src/channel/trust_policy/no_op_trust_policy.rs
implementations/rust/ockam/ockam_entity/src/error.rs
implementations/rust/ockam/ockam_entity/src/lib.rs
implementations/rust/ockam/ockam_entity/src/traits.rs

feat(rust): add trust policy

---

implementations/elixir/ockam/ockam/lib/ockam/examples/stream/bi_directional/local.ex
implementations/elixir/ockam/ockam/lib/ockam/worker.ex
implementations/elixir/ockam/ockam/test/ockam/worker_test.exs

Rebasing https://github.com/ockam-network/ockam/pull/1391

chore(elixir): add delayed init to ockam.worker

---

implementations/rust/ockam/ockam_core/src/routing/address.rs
implementations/rust/ockam/ockam_core/src/routing/route.rs

Rebase and CI run of https://github.com/ockam-network/ockam/pull/1470

chore(rust): Add a few unit tests to chore types.

---

examples/rust/get_started/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.toml
implementations/rust/ockam/signature_core/src/challenge.rs
implementations/rust/ockam/signature_core/src/commitment.rs
implementations/rust/ockam/signature_core/src/error.rs
implementations/rust/ockam/signature_core/src/message.rs
implementations/rust/ockam/signature_core/src/nonce.rs
implementations/rust/ockam/signature_core/src/proof_committed_builder.rs
implementations/rust/ockam/signature_core/src/signature_blinding.rs
implementations/rust/ockam/signature_core/src/util.rs

Bumps test coverage to ~86% from zero

test(rust): improve signature_core test coverage

---

implementations/elixir/ockam/ockam_hub/test/hub/service/alias_test.exs
implementations/elixir/ockam/ockam_hub/test/hub/service/echo_test.exs
implementations/elixir/ockam/ockam_hub/test/hub/web/web_test.exs
implementations/elixir/ockam/ockam_hub/test/test_helper.exs

Unit tests for Ockam.Hub.Service.Alias, Ockam.Hub.Service.Echo, Ockam.Hub.KafkaStreamHandler and Ockam.Hub.Web.
Related to this [issue](https://github.com/ockam-network/ockam/issues/1451).

unit tests to increase test cover

---

implementations/rust/ockam/ockam_vault_test_attribute/Cargo.lock
implementations/rust/ockam/ockam_vault_test_attribute/Cargo.toml
implementations/rust/ockam/ockam_vault_test_attribute/README.md

feat(rust): bump ockam_vault_test_attribute vers to v0.7.0

---

implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/ockam_vault_test_attribute/Cargo.lock
implementations/rust/ockam/ockam_vault_test_attribute/Cargo.toml
implementations/rust/ockam/ockam_vault_test_attribute/README.md

- feat(rust): bump ockam_vault_test_attribute vers to v0.7.0
- feat(rust): fix vault test attr dep

fix vault test attribute version

---

examples/rust/get_started/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/CHANGELOG.md
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.toml
implementations/rust/ockam/signature_bbs_plus/README.md
implementations/rust/ockam/signature_bls/CHANGELOG.md
implementations/rust/ockam/signature_bls/Cargo.lock
implementations/rust/ockam/signature_bls/Cargo.toml
implementations/rust/ockam/signature_bls/README.md
implementations/rust/ockam/signature_core/CHANGELOG.md
implementations/rust/ockam/signature_core/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.toml
implementations/rust/ockam/signature_core/README.md
implementations/rust/ockam/signature_ps/CHANGELOG.md
implementations/rust/ockam/signature_ps/Cargo.lock
implementations/rust/ockam/signature_ps/Cargo.toml
implementations/rust/ockam/signature_ps/README.md

feat(rust): release signature crates

---

implementations/rust/ockam/ockam_core/src/routing/address.rs
implementations/rust/ockam/ockam_core/src/routing/route.rs
implementations/rust/ockam/ockam_entity/src/authentication.rs
implementations/rust/ockam/ockam_entity/src/change/history.rs
implementations/rust/ockam/ockam_entity/src/entity.rs
implementations/rust/ockam/ockam_entity/src/imp.rs
implementations/rust/ockam/ockam_key_exchange_xx/src/state.rs
implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/lib.rs
implementations/rust/ockam/ockam_node/src/messages.rs
implementations/rust/ockam/ockam_node/src/node.rs
implementations/rust/ockam/ockam_node/src/relay.rs
implementations/rust/ockam/ockam_node/src/router.rs
implementations/rust/ockam/ockam_transport_tcp/src/init.rs
implementations/rust/ockam/ockam_transport_tcp/src/lib.rs
implementations/rust/ockam/ockam_transport_tcp/src/listener.rs
implementations/rust/ockam/ockam_transport_tcp/src/router.rs
implementations/rust/ockam/ockam_transport_tcp/src/sender.rs
implementations/rust/ockam/ockam_transport_websocket/src/init.rs
implementations/rust/ockam/ockam_transport_websocket/src/lib.rs
implementations/rust/ockam/ockam_transport_websocket/src/listener.rs
implementations/rust/ockam/ockam_transport_websocket/src/router.rs
implementations/rust/ockam/ockam_transport_websocket/src/sender.rs
implementations/rust/ockam/ockam_vault/src/hasher_impl.rs
implementations/rust/ockam/ockam_vault/src/verifier_impl.rs
implementations/rust/ockam/signature_bls/src/signature.rs
implementations/rust/ockam/signature_bls/src/signature_vt.rs
implementations/rust/ockam/signature_core/src/commitment.rs
implementations/rust/ockam/signature_ps/src/verifier.rs

chore(rust): fix clippy lints

---

implementations/elixir/ockam/ockam/config/config.exs
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/bi_directional/secure_channel.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/ping_pong.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/stream.ex
implementations/elixir/ockam/ockam/lib/ockam/node.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/client/bi_directional.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/client/bi_directional/publisher_proxy.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/client/consumer.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/client/publisher.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/index/worker.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/client.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/listener.ex
implementations/elixir/ockam/ockam/lib/ockam/worker.ex
implementations/elixir/ockam/ockam_kafka/lib/storage/kafka_storage.ex

- Make TCP client terminate gracefully
- Add timeouts to all stream protocol requests
- Reestablish the stream client session on timeout

fix(elixir): make stream session reliable by handling timeouts 

---

implementations/rust/ockam/ockam_entity/src/worker/entity_worker.rs

fix(rust): fix get_contact entity worker response type

---

examples/rust/get_started/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node_attribute/Cargo.lock
implementations/rust/ockam/ockam_node_no_std/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/ockam_vault_test_attribute/Cargo.lock
implementations/rust/ockam/ockam_vault_test_suite/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bls/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.lock
implementations/rust/ockam/signature_ps/Cargo.lock

feat(rust): bump crate dependencies, tokio et al

---

documentation/guides/draft/rust/get-started/xx-secure-channel-over-streams/README.md
documentation/guides/draft/rust/get-started/xx-secure-channel-over-streams/sequence.mmd
documentation/guides/draft/rust/get-started/xx-streams/README.md
documentation/guides/draft/rust/get-started/xx-streams/sequence.mmd
examples/rust/get_started/examples/14-stream-over-cloud-node-initiator.rs
examples/rust/get_started/examples/14-stream-over-cloud-node-responder.rs
examples/rust/get_started/examples/15-secure-channel-over-stream-over-cloud-node-initiator.rs
examples/rust/get_started/examples/15-secure-channel-over-stream-over-cloud-node-responder.rs

- Edit for consistent terminology
- Expand guide content
- Fix typos
- Bring rust `get_started` example code in line with guides
- Apply failing linter fixes

WIP docs: updates to stream guide from antoinevg/stream-guide

---

implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml
implementations/rust/ockam/ockam_vault_core/src/types.rs

Rebase of https://github.com/ockam-network/ockam/pull/1594#

chore: ockam_vault_core builds again with no-std feature

---

commitlint.config.js

ci(rust): ignore commit lint 664b8f72b90c4686c513042bcd72666418953f09

---

implementations/rust/ockam/ockam_vault/src/secret_impl.rs

feat(rust): add key id computation while importing secret in ockam_vault

---

documentation/use-cases/end-to-end-encryption-with-rust/README.md

Improve Guides

---

README.md
documentation/guides/rust/README.md
documentation/guides/rust/get-started/README.md
documentation/use-cases/end-to-end-encryption-with-rust/README.md

Co-authored-by: Mrinal Wadhwa <mrinal@ockam.io>
Co-authored-by: Daniil Fedotov <daniil@ockam.io>
Co-authored-by: Jared Stanbrough <jared@ockam.io>

docs: imporve guides

---

implementations/rust/ockam/ockam/src/lib.rs
implementations/rust/ockam/ockam/src/unique.rs

feat(rust): add a simple generator for unique, human-readable identifiers

---

documentation/guides/rust/README.md
examples/rust/get_started/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/ockam_vault_test_suite/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bls/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.lock
implementations/rust/ockam/signature_ps/Cargo.lock

- docs: remove backslash from setup command
- feat(rust): upgrade serde

setup command fix and updates

---

examples/rust/get_started/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/src/stream/consumer.rs
implementations/rust/ockam/ockam_channel/src/lib.rs
implementations/rust/ockam/ockam_channel/src/secure_channel.rs
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.toml
implementations/rust/ockam/ockam_entity/src/channel.rs
implementations/rust/ockam/ockam_entity/src/channel/listener.rs
implementations/rust/ockam/ockam_entity/src/channel/messages.rs
implementations/rust/ockam/ockam_entity/src/channel/secure_channel_worker.rs
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock

Rebase https://github.com/ockam-network/ockam/pull/1640

feat(rust): reimplement entity secure channels using workers

---

implementations/rust/ockam/ockam_entity/src/channel.rs
implementations/rust/ockam/ockam_entity/src/channel/listener.rs
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/src/address_record.rs
implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/lib.rs
implementations/rust/ockam/ockam_node/src/mailbox.rs
implementations/rust/ockam/ockam_node/src/node.rs
implementations/rust/ockam/ockam_node/src/relay.rs
implementations/rust/ockam/ockam_node/src/router.rs
implementations/rust/ockam/ockam_node/src/tests.rs

Verified that all examples are working with these changes

Context and Mailbox refactor

---

implementations/elixir/ockam/ockam/lib/ockam/stream/index/service.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/index/shard.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/workers/service.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/workers/stream.ex
implementations/elixir/ockam/ockam/lib/ockam/worker.ex
implementations/elixir/ockam/ockam_hub/lib/hub/kafka_topic_cleanup.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/kafka.ex
implementations/elixir/ockam/ockam_hub/lib/hub/worker_cleanup.ex
implementations/elixir/ockam/ockam_kafka/lib/config.ex
implementations/elixir/ockam/ockam_kafka/lib/index/kafka_offset_index.ex
implementations/elixir/ockam/ockam_kafka/lib/kafka.ex

Track last message timestamp coming through a worker.
Make stream service handle stream instance terminations.
Add a helper module to filter workers and stop them
using module name and callback on state.

chore(elixir): some helpers to clean up workers

---

examples/rust/get_started/Cargo.lock
examples/rust/ockam_kafka/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.toml
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bls/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.toml
implementations/rust/ockam/signature_ps/Cargo.lock

feat(rust): update heapless, trybuild, et al

---

examples/rust/get_started/Cargo.lock
examples/rust/ockam_kafka/Cargo.lock
implementations/rust/ockam/ockam/CHANGELOG.md
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam/README.md
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/ockam_vault_test_suite/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bls/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.lock
implementations/rust/ockam/signature_ps/Cargo.lock

- docs(rust): improve description of ockam rust crate
- docs(rust): improve description of ockam rust crate
- feat(rust): bump vers for doc update

point release for doc update

---

.github/workflows/documentation_examples_check.yml

ci: create documentation example cron job

---

.github/workflows/docker_base.yml
.github/workflows/docker_builder.yml
.github/workflows/docker_builder_base.yml
.github/workflows/docker_hub.yml
tools/docker/builder/Dockerfile

- ci: deploy docker from github ci
- ci: we shouldn't run docker builder on forks
- ci: indicate github package as docker base image
- ci: add repository dispatch on dockerfile update

ci: deploy docker from CI 

---

documentation/architecture/decisions/0003-crate-feature-flags.md

Rebase https://github.com/ockam-network/ockam/pull/1739

docs(rust): update adr 0003 crate feature flags

---

examples/rust/get_started/Cargo.lock
examples/rust/ockam_kafka/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bls/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.lock
implementations/rust/ockam/signature_ps/Cargo.lock

- bitflags  
- bitvec  
- bytes  
- ff  
- heapless  
- matches  
- memchr  
- tokio  
- trybuild  
- unicode-bidi  
- unicode-normalization
- volatile-register

feat(rust): update dependencies (tokio, heapless, trybuild, et al)

---

implementations/rust/ockam/ockam_vault/src/error.rs
implementations/rust/ockam/ockam_vault/src/secret_impl.rs

- feat(rust): remove clamping from curve25519 key generation
- feat(rust): add key validation during secret_import in ockam_vault
Rebase of [#1695](https://github.com/ockam-network/ockam/pull/1695)

feat(rust): add key validation during secret_import in ockam_vault

---

examples/rust/get_started/Cargo.lock
examples/rust/ockam_kafka/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock

feat(rust): update tracing-subscriber

---

.github/workflows/docker_base.yml
.github/workflows/docker_builder.yml
.github/workflows/docker_hub.yml

https://github.com/ockam-network/ockam/pull/1766

Rebase of metaclips/env secrets

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock

fix(rust): update lockfiles

---

implementations/rust/ockam/ockam_node_no_std/CHANGELOG.md
implementations/rust/ockam/ockam_node_no_std/Cargo.lock
implementations/rust/ockam/ockam_node_no_std/Cargo.toml
implementations/rust/ockam/ockam_node_no_std/src/lib.rs

feat(rust): initial publish of ockam_node_no_std

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node_no_std/Cargo.lock
implementations/rust/ockam/ockam_node_no_std/Cargo.toml
implementations/rust/ockam/ockam_node_no_std/README.md
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock

fix(rust): internal release process for no_std crate

---

implementations/rust/ockam/ockam_node/Cargo.toml

fix(rust): add explicit version for ockam_node_no_std dep

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/ockam_vault_test_suite/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bls/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.lock
implementations/rust/ockam/signature_ps/Cargo.lock

aead
aes
aes-gcm
blake2
bytes
cfg-if
cpufeatures
futures
futures-channel
futures-core
futures-executor
futures-io
futures-macro
futures-sink
futures-task
futures-util
ghash
libc
lock_api
managed
memchr
nb
ockam_core
parking_lot
parking_lot_core
polyval
serde
serde_derive
serde_json
sha-1
sha2
thiserror
thiserror-impl
tokio
vsss-rs

feat(rust): update aes,futures,serde and others

---

examples/rust/get_started/Cargo.lock
examples/rust/ockam_kafka/Cargo.lock

fix(rust): update example lockfiles

---

implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_channel/Cargo.toml
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node_no_std/Cargo.toml
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/Cargo.toml
implementations/rust/ockam/ockam_vault_sync_core/Cargo.toml

Prepare: https://github.com/ockam-network/ockam/pull/1803
1. Minor commit message change.
1. Squash and Rebase

docs(rust): change the word option to feature in cargo toml files

---

implementations/elixir/ockam/ockam_hub/config/runtime.exs
implementations/elixir/ockam/ockam_hub/lib/hub/service/token_lease_manager/cloud_service/influxdb.ex

This PR will modify the use endpoint for influxdb instead of hostname and port

chore(elixir): influxdb endpoint instead of hostname and port

---

implementations/elixir/ockam/ockam_hub/docs/token-lease-manager.md

This PR adds documentation for the implementation of *Token Lease Manager*.

docs(elixir): documentation for token lease manager

---

implementations/elixir/ockam/ockam_vault_software/native/vault/software/vault.c
implementations/rust/ockam/ockam_ffi/include/vault.h
implementations/rust/ockam/ockam_ffi/src/vault.rs

Rebase of https://github.com/ockam-network/ockam/pull/1801

Rebase of fix(rust): change size_t to uint32_t in C header file

---

examples/rust/get_started/Cargo.lock
examples/rust/secure_remote_access/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_core/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock

feat(rust): update tracing crates

---

examples/rust/get_started/Cargo.lock
examples/rust/secure_remote_access/Cargo.lock
implementations/rust/ockam/ockam/CHANGELOG.md
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam/README.md
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.lock

docs: correct link to secure remote access guide

---

.github/workflows/gradle.yml

ci: bump setup-java action to v2.3.0

---

.github/workflows/gradle.yml

ci: remove jdk14 from support matrix due to distro site errors

---

examples/rust/get_started/Cargo.lock
examples/rust/secure_remote_access/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bls/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.lock
implementations/rust/ockam/signature_ps/Cargo.lock

feat(rust): update heapless, tokio, et al

---

.github/workflows/cargo_update_check.yml

ci: perform `cargo update and check` on examples

---

documentation/architecture/decisions/0003-crate-feature-flags.md

docs: update crate-feature-flags decision

---

examples/rust/get_started/Cargo.lock
examples/rust/ockam_kafka/Cargo.lock
examples/rust/tcp_inlet_and_outlet/Cargo.lock
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/src/lib.rs
implementations/rust/ockam/ockam_entity/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_websocket/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/src/vault_sync.rs

- feat(rust): `define custom `clone` trait.
- feat(rust): implement `asynctryclone` for `valutsync`.
- fix(rust): fix method doc

Rebase of #1917 Define custom Clone trait for Async objects.

---

implementations/rust/ockam/ockam_core/src/error.rs

Update ockam_core::Result to allow generic error type

---

.github/workflows/cargo_update_check.yml
.github/workflows/documentation_examples_check.yml

jared/narrow GH action triggers

---

tools/docker/README.md
tools/docker/base/Dockerfile
tools/docker/builder/Dockerfile

update docker readme and build os version

update docker readme and build os version

---

Cargo.lock
NOTICE
implementations/rust/ockam/ockam_examples/example_projects/okta/management_service/Cargo.toml
implementations/rust/ockam/ockam_examples/example_projects/okta/management_service/src/main.rs
implementations/rust/ockam/ockam_examples/example_projects/okta/truck/Cargo.toml
implementations/rust/ockam/ockam_examples/example_projects/okta/truck/src/main.rs
tools/ockam-hub-cli/Cargo.toml
tools/ockam-hub-cli/src/auth/github.rs
tools/ockam-hub-cli/src/main.rs

chore(rust): replace `colored` with `owo-colors` in `ockam-hub-cli`

---

implementations/rust/ockam/ockam_macro/Cargo.toml

fix(rust): break circular dependency between ockam_macro and ockam_core in dev deps

---

Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.toml

fix(rust): add version for ockam_macro in ockam_core

---

implementations/rust/ockam/ockam_transport_websocket/src/lib.rs

refactor(rust): change `WebSocket` address type constant from 2 to 3

---

.github/workflows/ockam_features_check.yml

ockam feature ci check

---

Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/src/lib.rs

fix(rust): use `Zeroize` on sensitive values in x3dh protocol

---

implementations/rust/ockam/ockam/src/pipe/behavior/mod.rs
implementations/rust/ockam/ockam/src/pipe/behavior/ordering.rs
implementations/rust/ockam/ockam/src/pipe/behavior/resend.rs
implementations/rust/ockam/ockam/src/pipe/mod.rs
implementations/rust/ockam/ockam/src/pipe/receiver.rs
implementations/rust/ockam/ockam/src/pipe/sender.rs
implementations/rust/ockam/ockam/src/pipe/tests.rs

fix(rust): change context import from ockam_node to crate

---

examples/rust/tcp_inlet_and_outlet/Dockerfile

fix(rust): fix `tcp_inlet_and_outlet` example dockerfile

---

Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_channel/Cargo.toml
implementations/rust/ockam/ockam_command/Cargo.toml
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_entity/Cargo.toml
implementations/rust/ockam/ockam_examples/Cargo.toml
implementations/rust/ockam/ockam_executor/Cargo.toml
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_macros/Cargo.toml
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node_no_std/Cargo.toml
implementations/rust/ockam/ockam_transport_core/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_transport_websocket/Cargo.toml
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/Cargo.toml
implementations/rust/ockam/ockam_vault_sync_core/Cargo.toml
implementations/rust/ockam/ockam_vault_test_suite/Cargo.toml
implementations/rust/ockam/signature_bbs_plus/Cargo.toml
implementations/rust/ockam/signature_bls/Cargo.toml
implementations/rust/ockam/signature_core/Cargo.toml
implementations/rust/ockam/signature_ps/Cargo.toml

build(rust): change all crates to `-dev` version

---

integrations/suborbital/.runnable.yml
integrations/suborbital/README.md
integrations/suborbital/docker-compose-remote.yaml
integrations/suborbital/docker-compose.yaml

This PR documents how Ockam and [Suborbital](https://github.com/Suborbital) can be used together.

feat: add suborbital integration

---

tools/scripts/release/README.md
tools/scripts/release/changelog.sh
tools/scripts/release/crate-bump.sh
tools/scripts/release/crate-publish.sh
tools/scripts/release/crates-to-publish.sh
tools/scripts/release/publish-order.sh
tools/scripts/release/tagging.sh

This PR moves all Ockam release scripts to the Ockam repository. There is also a readme that shows how all scripts are to be used.

Publish scripts

---

.github/dependabot.yml

1. Use Rust Workspace
2. Add Labels for issues that Dependabot will create
3. Add Typescript Yarn Workspace

ci: improve dependabot configuration

---

.github/workflows/commits.yml

1. rename commitlint workflow to commits
2. improve error messages

ci: improve commits workflow

---

documentation/guides/rust/get-started/04-transport/README.md

docs: change wrong number of next step

---

Cargo.toml
examples/rust/file_transfer/Cargo.toml
examples/rust/get_started/Cargo.toml
examples/rust/ockam_kafka/Cargo.toml
examples/rust/tcp_inlet_and_outlet/Cargo.toml
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_channel/Cargo.toml
implementations/rust/ockam/ockam_command/Cargo.toml
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_entity/Cargo.toml
implementations/rust/ockam/ockam_examples/Cargo.toml
implementations/rust/ockam/ockam_executor/Cargo.toml
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_macros/Cargo.toml
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_transport_core/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_transport_websocket/Cargo.toml
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_sync_core/Cargo.toml
implementations/rust/ockam/ockam_vault_test_suite/Cargo.toml
implementations/rust/ockam/signature_bbs_plus/Cargo.toml
implementations/rust/ockam/signature_bls/Cargo.toml
implementations/rust/ockam/signature_core/Cargo.toml
implementations/rust/ockam/signature_ps/Cargo.toml
tools/docs/example_blocks/Cargo.toml
tools/docs/example_runner/Cargo.toml

Documented in #2204 
Add `rust-version` to all the `Cargo.toml`
N/A
This closes #2204

feat(rust): Add rust-version to each Cargo.toml

---

.devcontainer/Dockerfile
.github/actions/cargo_home_cache/action.yml
.github/actions/cargo_target_dir_cache/action.yml
.github/actions/elixir_cache/action.yml
.github/actions/gradle_cache/action.yml
.github/workflows/all.yml
.github/workflows/documentation.yml
.github/workflows/elixir.yml
.github/workflows/rust.yml
examples/rust/ockam_kafka/Dockerfile
examples/rust/tcp_inlet_and_outlet/Dockerfile
tools/docker/builder/Dockerfile

1. Add zig
2. Add nodejs
3. Bump cmake version
4. Bump rust version
5. Bump erlang version
6. Bump elixir version
7. Bump jdk version
8. Update pinned versions of builder image

build: update builder container image

---

implementations/rust/ockam/ockam_entity/src/contact.rs
implementations/rust/ockam/ockam_entity/src/credential/entity_credentials.rs
implementations/rust/ockam/ockam_entity/src/credential/error.rs
implementations/rust/ockam/ockam_entity/src/credential/messages.rs
implementations/rust/ockam/ockam_entity/src/credential/profile_state_credentials.rs
implementations/rust/ockam/ockam_entity/src/credential/workers/holder.rs
implementations/rust/ockam/ockam_entity/src/credential/workers/issuer.rs
implementations/rust/ockam/ockam_entity/src/credential/workers/listener.rs
implementations/rust/ockam/ockam_entity/src/credential/workers/verifier.rs
implementations/rust/ockam/ockam_examples/example_projects/credentials/Cargo.toml
implementations/rust/ockam/ockam_examples/example_projects/credentials/src/bin/bob.rs
implementations/rust/ockam/ockam_examples/example_projects/credentials/src/bin/door.rs
implementations/rust/ockam/ockam_examples/example_projects/credentials/src/bin/office.rs
implementations/rust/ockam/ockam_vault/src/secret_impl.rs

Rebase:
- https://github.com/ockam-network/ockam/pull/2411

fix(rust): fix credentials build failure

---

tools/docker/builder/Dockerfile

Install libdbus to docker builder image for #2433 CI to pass

Add libdbus to docker builder image

---

tools/scripts/release/crate-bump.sh
tools/scripts/release/crate-publish.sh
tools/scripts/release/dev-bump.sh

Rebase:
- https://github.com/ockam-network/ockam/pull/2436

ci: bump crates using name specified in cargo.toml

---

tools/docs/example_blocks/README.md
tools/docs/example_runner/README.md

READMEs that describe the example tools. @thomcc please let me know if this makes sense

docs(rust): readmes for example tools

---

implementations/rust/ockam/ockam_node/src/compat.rs
implementations/rust/ockam/ockam_node/src/compat/mutex.rs
implementations/rust/ockam/ockam_node/src/compat/rwlock.rs
implementations/rust/ockam/ockam_node/src/lib.rs

RwLock and Mutex in ockam_node compat (rebased)

---

.github/actions/cargo_home_cache/action.yml
.github/actions/cargo_target_dir_cache/action.yml
.github/actions/cargo_target_dir_pre_cache/action.yml
.github/actions/elixir_cache/action.yml
.github/actions/gradle_cache/action.yml
.github/workflows/elixir.yml
.github/workflows/rust.yml

investigate caching (rebased)

---

Cargo.lock
implementations/rust/ockam/ockam/src/lib.rs
implementations/rust/ockam/ockam/src/workers/echoer.rs
implementations/rust/ockam/ockam/src/workers/mod.rs
implementations/rust/ockam/ockam_core/src/routing/address.rs
implementations/rust/ockam/ockam_macros/src/node_test_attribute/parser.rs
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/src/heartbeat.rs
implementations/rust/ockam/ockam_node/src/lib.rs
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/src/router/mod.rs
implementations/rust/ockam/ockam_transport_tcp/src/workers/sender.rs
implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs

Doing this in one PR to avoid having to wait through the land/rebase flow 6 times >_>
Fixes #2504, #2505, #2506, #2507, #2508, #2509

Rebase/rollup of #2504, #2505, #2506, #2507, #2508, #2509

---

.devcontainer/Dockerfile
.github/actions/cargo_home_cache/action.yml
.github/actions/cargo_target_dir_cache/action.yml
.github/actions/elixir_cache/action.yml
.github/actions/gradle_cache/action.yml
.github/workflows/all.yml
.github/workflows/documentation.yml
.github/workflows/elixir.yml
.github/workflows/rust.yml
examples/rust/ockam_kafka/Dockerfile
examples/rust/tcp_inlet_and_outlet/Dockerfile

Rebase of #2483

---

implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/error.rs
implementations/rust/ockam/ockam_node/src/lib.rs
implementations/rust/ockam/ockam_node/src/messages.rs
implementations/rust/ockam/ockam_node/src/relay/processor_relay.rs
implementations/rust/ockam/ockam_node/src/relay/worker_relay.rs
implementations/rust/ockam/ockam_node/src/router/mod.rs
implementations/rust/ockam/ockam_node/src/router/record.rs
implementations/rust/ockam/ockam_node/src/router/stop_processor.rs
implementations/rust/ockam/ockam_node/src/router/stop_worker.rs
implementations/rust/ockam/ockam_node/src/router/utils.rs
implementations/rust/ockam/ockam_node/src/tests.rs

Rebase of worker readiness PR

---

.devcontainer/Dockerfile
.github/actions/cargo_home_cache/action.yml
.github/actions/cargo_target_dir_cache/action.yml
.github/actions/elixir_cache/action.yml
.github/actions/gradle_cache/action.yml
.github/workflows/all.yml
.github/workflows/documentation.yml
.github/workflows/elixir.yml
.github/workflows/rust.yml
examples/rust/ockam_kafka/Dockerfile
examples/rust/tcp_inlet_and_outlet/Dockerfile

Bump workflow builder image SHA

bump ci and docker builder image

---

examples/elixir/get_started/07-routing-via-remote-forwarder-responder.exs
examples/elixir/get_started/08-secure-channel-over-remote-forwarder-responder.ex
examples/elixir/get_started/setup.exs
implementations/elixir/ockam/ockam/lib/ockam/workers/remote_forwarder.ex

fix: update elixir api in forwarder examples

---

tools/scripts/release/README.md
tools/scripts/release/crate-bump.sh

Rebase of #2549

---

implementations/rust/ockam/ockam_transport_ble/Cargo.toml

Rebase of #2550

---

documentation/use-cases/secure-remote-access-tunnels/README.md
tools/docs/check_documentation.sh

Rebase of neil2468/fix_variable_check_documentation

---

tools/scripts/release/README.md
tools/scripts/release/changelog.sh

Rebase of git-cliff temporary fix

---

.github/workflows/commits.yml

Rebase of commit_lint_fix

---

examples/elixir/tcp_inlet_and_outlet/01-inlet-outlet.exs
examples/elixir/tcp_inlet_and_outlet/02-inlet.exs
examples/elixir/tcp_inlet_and_outlet/02-outlet.exs
examples/elixir/tcp_inlet_and_outlet/03-inlet.exs
examples/elixir/tcp_inlet_and_outlet/03-outlet.exs
examples/elixir/tcp_inlet_and_outlet/04-inlet.exs
examples/elixir/tcp_inlet_and_outlet/04-outlet.exs
examples/elixir/tcp_inlet_and_outlet/setup.exs
examples/elixir/tcp_inlet_and_outlet/waiter.exs
implementations/elixir/ockam/ockam/lib/ockam/protocol/bare_extended.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/portal/inlet_listener.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/portal/inlet_worker.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/portal/outlet_worker.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/portal/tunnel_protocol.ex
implementations/elixir/ockam/ockam/test/ockam/transport/portal/outlet_worker_tests.exs
implementations/elixir/ockam/ockam/test/ockam/transport/portal/tunnel_protocol_tests.exs

feat(elixir): implement portals protocol

---

README.md
tools/docs/check_documentation.sh

Rebase of #2633

---

implementations/rust/ockam/ockam/src/lib.rs
implementations/rust/ockam/ockam/tests/node/std/pass_with_macro_attr_crate.rs
implementations/rust/ockam/ockam_core/src/lib.rs
implementations/rust/ockam/ockam_macros/src/node_attribute.rs
implementations/rust/ockam/ockam_transport_tcp/src/router/mod.rs
implementations/rust/ockam/ockam_transport_tcp/src/transport.rs

Rebase of adrian/ga-small-issues

---

implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/router/record.rs
implementations/rust/ockam/ockam_node/src/router/stop_worker.rs
implementations/rust/ockam/ockam_node/src/tests.rs

Rebased both at the same time.
Closes #2627
Closes #2666

Rollup of two PRs (#2666 and #2627)

---

implementations/elixir/ockam/ockam_hub/test/hub/service/discovery_test.exs

Some services registry records are not cleaned up before another test runs. #2669
Use different addresses in different tests

fix(elixir): remove some race conditions in elixir tests

---

implementations/elixir/ockam/ockam/lib/ockam/telemetry_logger.ex

chore(elixir): add logging telemetry events

---

implementations/elixir/ockam/ockam/lib/ockam/mini_cbor.ex
implementations/elixir/ockam/ockam/mix.exs
implementations/elixir/ockam/ockam/mix.lock
implementations/elixir/ockam/ockam_cloud_node/mix.lock
implementations/elixir/ockam/ockam_kafka/mix.lock
implementations/elixir/ockam/ockam_services/mix.lock

There is a number of issues with current message encoding format is discussed in https://github.com/ockam-network/ockam/issues/2496
This PR adds CBOR library and mini_cbor map optimization.
Addresses https://github.com/ockam-network/ockam/issues/2687

feat(elixir): cbor library and mini_cbor map optimization
