chain/chain_test.go
chain/mock.go

This pull request adds unit test coverage to the chain package. Proposed follow-on work is extending the `mockNode{}` type to support more robust testing, and returning an error from the `Option` type. The latter isn't really necessary yet however since none of the `Option` implementations call the types which are passed to them, they are simply there to set values. However, we may want to consider validation on the values passed in order to ensure no nil type or other exceptions occur when these values are accessed later on.

test: add unit test coverage to chain package

---

implementations/c/include/ockam/error.h
implementations/c/include/ockam/memory.h
implementations/c/include/ockam/vault.h
implementations/c/include/ockam/vault/host.h
implementations/c/source/ockam/memory/stdlib.c
implementations/c/source/ockam/vault/host/mbedcrypto.c
implementations/c/test/ockam/vault/atecc508a/source/test_atecc508a.c
implementations/c/test/ockam/vault/atecc608a/source/test_atecc608a.c
implementations/c/test/ockam/vault/build.gradle
implementations/c/test/ockam/vault/mbedcrypto/CMakeLists.txt
implementations/c/test/ockam/vault/mbedcrypto/build.gradle
implementations/c/test/ockam/vault/mbedcrypto/config/vault_config.h
implementations/c/test/ockam/vault/mbedcrypto/settings.gradle
implementations/c/test/ockam/vault/mbedcrypto/source/test_mbedcrypto.c
implementations/c/test/ockam/vault/source/key_ecdh.c
implementations/c/test/ockam/vault/source/print.c

Add Ockam Vault support for the following operations using mbed crypto: #69 
-Random Number Generation
-Key Generation/Public Key Retrieval
-ECDH
-HKDF
-AES GCM 128/192/256
Test application target:
-Raspberry Pi

feat(implementation/c): Vault for mbed crypto

---

implementations/c/include/ockam/error.h
implementations/c/include/ockam/vault.h
implementations/c/include/ockam/vault/host.h
implementations/c/source/ockam/vault/host/mbedcrypto.c
implementations/c/source/ockam/vault/vault.c
implementations/c/test/ockam/vault/atecc508a/source/test_atecc508a.c
implementations/c/test/ockam/vault/atecc608a/source/test_atecc608a.c
implementations/c/test/ockam/vault/include/test_vault.h
implementations/c/test/ockam/vault/mbedcrypto/CMakeLists.txt
implementations/c/test/ockam/vault/mbedcrypto/config/mbed_crypto_config.h
implementations/c/test/ockam/vault/mbedcrypto/source/test_mbedcrypto.c
implementations/c/test/ockam/vault/source/key_ecdh.c
implementations/c/tools/cmake/third-party/mbedcrypto.cmake

Add new Vault API to allow writing private keys to Vault. Support
limited to mbed-crypto. All other platforms report feature unimplemented.

feat(implementations/c): Write Curve25519 private keys to mbed-crypto

---

implementations/c/source/ockam/vault/host/mbedcrypto.c
implementations/c/source/ockam/vault/tpm/microchip/atecc608a.c
implementations/c/test/ockam/vault/source/aes_gcm.c

Modify parameter checking for mbed-crypto and ATECC608A to allow
zero-length payloads. Add test case to validate change.
Config check for ATECC608A HKDF had incorrect define, update to correct
define.

fix(implementations/c): Allow zero-length payload for AES GCM

---

build.gradle
implementations/c/test/ockam/vault/build.gradle
tools/gradle/plugins/builder/src/main/groovy/network/ockam/gradle/builders/BuildersPlugin.groovy

Improves handling of builder detection when building in subdirectories, can now invoke things like `buildC` directly without having to specify a Docker-specific task, or export environment variables

build: fixes to docker builder detection

---

implementations/c/include/ockam/memory.h
implementations/c/lib/memory/stdlib.c
implementations/c/lib/vault/default/default.c
implementations/c/lib/vault/tests/aes_gcm.c
implementations/c/lib/vault/tests/hkdf.c
implementations/c/lib/vault/tests/key_ecdh.c

In order to integrate the C memory functions with Rust's
Alloc/GlobalAlloc, a size parameter is needed in OckamMemory's Free
function. Caller's of Free should always pass in the size they
allocated, but the underlying implementation of Free may choose to
enforce or ignore the size parameter.

feat(c): add size parameter to memory free

---

implementations/elixir/build.gradle
implementations/elixir/lib/channel.ex
implementations/elixir/lib/transport.ex
implementations/elixir/lib/transport/socket.ex
implementations/elixir/lib/transport/tcp/connection.ex
implementations/elixir/test/integration/handshake_test.exs
implementations/elixir/test/transport/transport_test.exs

/cc @mrinalwadhwa 
This commit should fix the hang in CI. The problem seems to be that the socket metadata was not correctly updated in one place when notified that an async receive was ready to be received, causing the subsequent call to `recv` to hang indefinitely somewhere in the VM. I'm not sure why that wouldn't result in an error, but I haven't bothered to dig into that now that I know what the cause is. There are a few unrelated changes here that I made while testing, but which will be needed regardless, and since they are all focused on the socket handling code, it seems appropriate to merge them here.
I've also disabled the two integration tests with C, since those are broken until my PR that updates the Elixir implementation to use the wire protocol is merged (that PR will …

fix: random hangs in ci

---

implementations/c/lib/key_agreement/tests/xx/xx_test.c
implementations/c/lib/transport/tests/posix_socket/tcp/test_tcp.h
implementations/c/lib/transport/tests/posix_socket/tcp/test_tcp_client.c
implementations/c/lib/transport/tests/posix_socket/tcp/test_tcp_server.c
implementations/c/lib/vault/default/tests/test_default.c

This PR contains two improvements:
1. Add getopts to the TCP test to allow for a non-fixed path to the fixtures directory. IP and Port are also added to getopts.
2. Check the error return for the default vault test create step.

Improve Vault and Transport tests

---

documentation/concepts/vaults.md

Documentation change to fix the broken link on the Vault concept page that references the Vault proposal. 
I could only find the Vault proposal as a WIP on a branch and PR. Maybe the link should go to the Vault guide instead.

docs: fix the link to the vault proposal, clarify its draft state

---

implementations/rust/Cargo.toml
implementations/rust/vault/Cargo.toml
implementations/rust/vault/src/error.rs
implementations/rust/vault/src/lib.rs

Adds crate specific error that also converts to FFI integer values found in implementations/c/include/ockam/{vault.h, error.h}

Added errors

---

implementations/c/ockam/vault/rust/tests/vault.c
implementations/rust/vault/include/vault.h
implementations/rust/vault/src/ffi/mod.rs
implementations/rust/vault/src/ffi/types.rs
implementations/rust/vault/src/types.rs

Change ffi handle from C string to unsigned int 64. This removes the necessity of freeing the string handle once finished.

avoid string allocation to prevent memory leaks

---

implementations/elixir/README.md
implementations/elixir/lib/ockam/vault/software.ex
implementations/elixir/mix.exs
implementations/elixir/native/CMakeLists.txt
implementations/elixir/native/vault/CMakeLists.txt
implementations/elixir/native/vault/software/CMakeLists.txt
implementations/elixir/native/vault/software/nifs.c
implementations/elixir/test/ockam/channel_test.exs
implementations/elixir/test/ockam/vault/software_test.exs

1. docs(elixir): add readme with build instructions
2. feat(elixir): add software vault nif and nif compiler
3. test(elixir): disable broken channel test 
(this test is broken because of there is not working vault, we can re-enable it once we add that back in)
This doesn't yet tackle the cmake support needed to find other rust/c modules.

Add support for natively implemented vault functions, so elixir can call C

---

implementations/e/.formatter.exs
implementations/e/.gitignore
implementations/e/README.md
implementations/e/applications/ockam/lib/ockam.ex
implementations/e/applications/ockam/mix.exs
implementations/e/applications/ockam/test/ockam_test.exs
implementations/e/applications/ockam/test/test_helper.exs
implementations/e/build.gradle
implementations/e/configuration/config.exs
implementations/e/mix.exs
implementations/e/mix.lock
implementations/e/settings.gradle

this sets up an elixir umbrella project boilerplate in parallel to our current elixir code in `implementations/e`.
this will replace the current elixir implementation in a few days.

umbrella boilerplate

---

implementations/e/applications/ockam_vault_software/lib/kex_rust.ex
implementations/e/applications/ockam_vault_software/native/vault/key_exchange/CMakeLists.txt
implementations/e/applications/ockam_vault_software/native/vault/key_exchange/nifs.c
implementations/e/applications/ockam_vault_software/test/kex_rust_test.exs
implementations/rust/kex/include/kex.h
implementations/rust/kex/src/error.rs
implementations/rust/kex/src/ffi/mod.rs
implementations/rust/kex/src/ffi/types.rs
implementations/rust/kex/src/lib.rs

This PR adds following:
1. C header with kex interface for nifs
2. C nifs
3. Elixir functions for nifs
4. 1 very basic elixir test
5. Placeholders for all kex rust ffi functions
What needs to be done:
1. Improve storage for ffi instances, so that vault handle could be used as a dependency to rust kex
2. Finish rust ffi layer (should be pretty straightforward after 1 is done)

feat(elixir): add key exchange to rust <-> elixir ffi

---

implementations/rust/Cargo.lock
implementations/rust/Cargo.toml
implementations/rust/common/src/commands.rs
implementations/rust/message/src/message.rs
implementations/rust/node/Cargo.toml
implementations/rust/node/src/node.rs
implementations/rust/router/Cargo.toml
implementations/rust/router/src/router.rs
implementations/rust/transport/Cargo.toml
implementations/rust/transport/src/transport.rs

- node: Spin up a thread for router channels and transport.
Implement prototype channel, register channel with router
Send message to channel, channel sends to router, router
sends to transport
- commands: combine all ockam command types into a single enum
- message: implement helper functions for manipulating routes and addresses
- udp transport: implement mapping of ip address string to socket, implement
polling loop to process ockam commands and socket events
- router: implement polling loop to process routing commands

feat(rust): implement basic node, test basic routing and udp transport

---

implementations/rust/Cargo.toml

Adds `daemon` crate to new list of `default-members` in the workspace
This allows more convenient use of `cargo`

chore(rust): add daemon to default-members list for cargo

---

implementations/rust/common/src/commands.rs
implementations/rust/daemon/src/bin/ockamd.rs
implementations/rust/daemon/src/lib.rs
implementations/rust/daemon/src/node.rs
implementations/rust/daemon/src/worker.rs
implementations/rust/message/src/lib.rs

To test, use these commands from `implementations/rust`:
---
no transport, echo stdin -> stdout:
```sh
cargo  run --bin ockamd -- \
--role=init \
--output=stdout \
--channel-responder-address=33333333 \
--worker-address=01242020 \
--identity-name=default \
--responder-public-key=1234
```
---
over UDP transport, no secure channels:
1. start ockamd,
```sh
cargo  run --bin ockamd -- \
--role=init \
--output=udp://127.0.0.1:34254 \
--channel-responder-address=33333333 \
--worker-address=01242020 \
--identity-name=default \
--responder-public-key=1234
```
2. and separately, run:
```rust
use std::net::UdpSocket;
fn main() {
let socket = UdpSocket::bind("127.0.0.1:34254").expect("failed to bind socket address");
println!("udp socket: 127.0.0.1:34254");
loop {
let mut buf = [0; 32]; …
```

feat(rust): use basic worker to process message

---

implementations/rust/channel/src/lib.rs

This is a requirement for the initiator in `ockamd` to verify the public key of the responder. 
However, I think it is limited to that direction -- if so, would it also be necessary to add this public key data to the message in the `KeyAgreementM3` branch? lastly, then would it be in the case where there is a `pending_message`, or None, or both?

feat(rust): add remote public key to the message body for completed kex

---

implementations/rust/channel/src/lib.rs
implementations/rust/kex/src/error.rs
implementations/rust/kex/src/lib.rs
implementations/rust/kex/src/x3dh.rs
implementations/rust/kex/src/xx.rs

Update key exchange to allow an predefined identity key

feat(rust): add optional identity key when creating exchange

---

.github/workflows/ci.yml

This will fix the CI sequencing so we only build Rust code once and then clean up at the end.

ci: reorder steps to avoid multiple builds

---

.dockerignore
tools/docker/ockam-dev/Dockerfile
tools/docker/rust/Dockerfile.ockamd

From the `ockam-network/ockam` project root:
`docker build -t ockam-dev -f tools/docker/ockam-dev/Dockerfile .` 
- _this will take a while, and currently produces a >3GB image_
`docker build -t ockamd:0.1.0 -f tools/docker/rust/Dockerfile.ockamd .`
- _very fast since dependencies are pre-compiled in ockam-dev_
Eventually I would like to push these to Docker hub, but they will be the basis for the docker-compose setup for the telegraf/influx end-to-end demo.

build: add dockerfiles for ockam-dev as a builder image and ockamd

---

implementations/rust/channel/src/lib.rs
implementations/rust/daemon/src/cli.rs
implementations/rust/daemon/src/config.rs
implementations/rust/daemon/src/initiator.rs
implementations/rust/daemon/src/node.rs
implementations/rust/daemon/src/responder.rs
implementations/rust/node/src/node.rs

- channel now sends responder public key in message-body of channel
completion message
- ockamd-initiator will panic if a responder public key is supplied and
it doesn't match the computed responder key

feat(rust): make ockamd panic if supplied public key doesn't match computed key

---

implementations/rust/channel/src/lib.rs
implementations/rust/daemon/src/initiator.rs
implementations/rust/daemon/src/worker.rs
implementations/rust/message/src/lib.rs

if the address isn't valid, drop the message and print a warning

feat(rust): make ockamd responder check for valid worker address

---

implementations/rust/Cargo.lock
implementations/rust/daemon/Cargo.toml
implementations/rust/daemon/src/cli.rs
implementations/rust/daemon/src/config.rs
implementations/rust/daemon/src/responder.rs
implementations/rust/daemon/src/worker.rs

implement the full data path: 
`telegraf -> ockamd --(secure channel)--> ockamd -> influxdb`
introduces an "addon" CLI paramater, which is meant to simplify the usage of various integrations. to use the InfluxDB addon, you run the responder as such:
`ockamd --role=responder --local-socket=127.0.0.1:52440 --addon=influxdb,$DB_NAME,http://127.0.0.1:8086`
This will configure `ockamd` to send encrypted messages received by responder to InfluxDB over HTTP using the database name and URL provided.

feat(rust): implement the influxdb addon configuration, write message over http

---

implementations/rust/daemon/README.md
implementations/rust/daemon/src/cli.rs
tools/docker/demo/influxdb.sh
tools/docker/influxdb/Dockerfile.influxdb-ockamd
tools/docker/influxdb/entrypoint.sh
tools/docker/rust/Dockerfile.ockamd
tools/docker/rust/Dockerfile.router
tools/docker/telegraf/Dockerfile.telegraf-ockamd
tools/docker/telegraf/telegraf.conf

1. build the local docker files to get the demo images:
```sh
docker build -t ockam/ockam-dev -f tools/docker/ockam-dev/Dockerfile . # base builder image
docker build -t ockam/ockamd:0.1.0 -f tools/docker/rust/Dockerfile.ockamd . # builds v0.1.0 of `ockamd`
docker build -t ockam/telegraf-ockamd:0.1.0 -f tools/docker/telegraf/Dockerfile.telegraf-ockamd . # builds  v0.1.0 of `telegraf-ockamd`
docker build -t ockam/influxdb-ockamd:0.1.0 -f tools/docker/influxdb/Dockerfile.influxdb-ockamd . # builds v0.1.0 of `influxdb-ockamd`
```
2. run `InfluxDB` and `ockamd` as the responder end:
```sh
./tools/docker/demo/influxdb.sh influxdb-ockamd
```
3. run the `Telegraf` agent and `ockamd` as the initiator end:
```sh
./tools/docker/demo/influxdb.sh telegraf-ockamd $COPIED_RESPONDER_PUBLIC_KEY
```
4. …

build: add dockerfile for telegraf-ockamd and influxdb-ockamd

---

implementations/rust/vault/src/ffi/mod.rs

Previously when encrypt received a 0-byte message it would throw an error. However, encrypting a zero byte message is acceptable. This removes the 0-byte check but still checks for an invalid pointer.

fix(rust): allow empty messages to vault encrypt

---

tools/docker/demo/influxdb.sh
tools/docker/influxdb/Dockerfile.influxdb-ockamd
tools/docker/rust/Dockerfile.ockamd
tools/docker/rust/Dockerfile.router
tools/docker/telegraf/Dockerfile.telegraf-ockamd

feat: update dockerfiles and scripts to use ockamd version 0.10.0
feat: build ockamd in release mode in dockerfile

update dockerfiles and scripts to use ockamd version 0.10.0

---

implementations/rust/ockam_macros/Cargo.toml
implementations/rust/ockam_macros/src/lib.rs

This crate holds macros for the Ockam core. One macro is defined, an async wrapper around the `executor` crate. When we add `tokio` support, we can add it similarly.

feat(rust): ockam_macros proc macro crate

---

implementations/rust/examples/examples/worker_builder.rs
implementations/rust/examples/examples/worker_from_closure.rs
implementations/rust/examples/examples/worker_mailbox.rs
implementations/rust/examples/examples/worker_send.rs

Includes more Worker examples:
1. WorkerBuilder
2. Closure based workers
3. External mailbox
4. Sending a message to a Worker

feat(rust): additional worker examples

---

documentation/concepts/enrollment.md

Just fixing a small typo I noticed while reading through the docs.

docs: fix typo in enrollment document

---

implementations/rust/ockam/ockam/src/entity/profile.rs
implementations/rust/ockam/ockam/src/entity/profile/verification.rs

This starts with the key signature verification method and tries to structure it as a collection of verification policies.
Along the lines of https://w3c.github.io/did-spec-registries/#ed25519verificationkey2018

prototype of profile verification policies and purpose

---

implementations/rust/examples/workers/Cargo.lock
implementations/rust/examples/workers/Cargo.toml
implementations/rust/examples/workers/examples/worker.rs
implementations/rust/examples/workers/examples/worker_builder.rs
implementations/rust/examples/workers/examples/worker_send.rs
implementations/rust/ockam/ockam/src/node.rs
implementations/rust/ockam/ockam/src/queue.rs
implementations/rust/ockam/ockam/src/worker.rs

1. Remove started and stopped handler callbacks
2. Made `WorkerBuilder::start` async
3. Deleted closure related code.
4. Deleted old tests: Rust unit tests can't use async. We will need to rewrite tests using `tokio_test`.
5. All tests now use async

feature(rust): use async/await for worker creation

---

implementations/rust/ockam/ockam_node/CHANGELOG.md
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/README.md

Adds a `description` to the Cargo.toml, required by crates.io.

chore(rust): ockam_node crate v0.1.1

---

implementations/rust/ockam/ockam_node/Cargo.toml

Removing wildcard dependency which is disallowed on crates.io

chore(rust): remove wildcard dep from node crate

---

implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/README.md

Releases ockam_node crate with crates.io TOML fixes

Release ockam_node crate v0.1.2

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_core/CHANGELOG.md
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_core/README.md
implementations/rust/ockam/ockam_credential/Cargo.lock
implementations/rust/ockam/ockam_credential/Cargo.toml
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml

- Explicit `alloc`, `no_std`, and `std` features.
- Generalized `Address` implementation.
- Global crate lib facade wrapper around `std` and `core` re-exports, for cross-feature compatibility.
- Message trait base implementation.
- Improved documentation.

feat(rust): ockam_core crate v0.3.0

---

implementations/rust/ockam/ockam_credential/CHANGELOG.md
implementations/rust/ockam/ockam_credential/Cargo.lock
implementations/rust/ockam/ockam_credential/Cargo.toml

- Only available in std mode
- `Claim` - information that has been signed in a credential
- `ClaimType` - the data encoding for a claim
- `CredentialOffer` - information from an issuer that will be in a credential
- `Credential` - a cryptographic signature with claims
- `BlindCredential` - a cryptographic blinded signature with claims
- `CredentialError::MismatchedAttributesAndClaims` - schema attributes and claims do not match
- `CredentialError::MismatchedAttributeClaimType` - attribute type and claim type do not match
- `CredentialError::InvalidClaim` - claim data cannot be mapped to a valid cryptographic value
- `Issuer` - methods for issuing credentials and blinded credentials

ockam_credential crate v0.2.0

---

implementations/rust/ockam/ockam_vault/Cargo.toml

Removing extraneous keywords from ockam_vault toml

fix(rust): ockam_vault: crates.io only allows 5 keywords

---

implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/error.rs

This change improves the context API so that all calls can be used with a `?`, instead of having to unwrap or map errors manually.

chore(rust): context receive returns result

---

implementations/rust/examples/node/Cargo.toml
implementations/rust/examples/node/examples/create_node_with_macro.rs
implementations/rust/examples/node/examples/create_node_without_macro.rs
implementations/rust/examples/node/examples/create_ping_pong_node.rs
implementations/rust/examples/worker/Cargo.toml
implementations/rust/examples/worker/examples/worker_cancel_reply.rs
implementations/rust/examples/worker/examples/worker_get_reply.rs
implementations/rust/examples/worker/examples/worker_initialize.rs
implementations/rust/examples/worker/examples/worker_ring_benchmark.rs
implementations/rust/examples/worker/examples/worker_send_message.rs
implementations/rust/examples/worker/examples/worker_stateful.rs
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam/src/lib.rs
implementations/rust/ockam/ockam/tests/node_attribute/can_be_used_on_any_fn.rs
implementations/rust/ockam/ockam/tests/node_attribute/can_be_used_on_any_fn_ockam_use_as_o.rs
implementations/rust/ockam/ockam/tests/node_attribute/can_be_used_on_main.rs
implementations/rust/ockam/ockam/tests/node_attribute/fails_if_more_than_one_arg.rs
implementations/rust/ockam/ockam/tests/node_attribute/fails_if_more_than_one_arg.stderr
implementations/rust/ockam/ockam_core/src/worker.rs
implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/lib.rs
implementations/rust/ockam/ockam_node/src/mailbox.rs
implementations/rust/ockam/ockam_node/src/relay.rs

This PR changes the context API and worker traits to be async again, and updates all examples to use this API.

chore(rust): change node, context, and worker api to be async again

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_core/CHANGELOG.md
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_core/README.md
implementations/rust/ockam/ockam_core/src/address.rs
implementations/rust/ockam/ockam_core/src/lib.rs
implementations/rust/ockam/ockam_core/src/message.rs
implementations/rust/ockam/ockam_core/src/worker.rs
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_router/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml

- Auto-implemenation of the `Message` trait for certain types.
- The `Worker` trait and its methods are now async.

feat(rust): ockam_core crate v0.4.0

---

implementations/rust/ockam/ockam_ffi/Cargo.toml

Too many keywords for crates.io

fix(rust): limit ockam_ffi keywords to 5

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_node/CHANGELOG.md
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/README.md
implementations/rust/ockam/ockam_transport_tcp/src/listener.rs

- Worker mailbox queues.
- Support new Context API in `ockam_node_attribute`
- Message cancellation.
- Receive returns a result.
- Refactor of `node` API.
- Node, Context and Worker APIs are now async.
- Worker initialization is now async.
- Dependency updates.
- Context `send_message` no longer silently eats errors.

feat(rust): ockam_node v0.3.0

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_core/src/lib.rs
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_router/Cargo.lock
implementations/rust/ockam/ockam_router/Cargo.toml
implementations/rust/ockam/ockam_router/src/local_router.rs
implementations/rust/ockam/ockam_router/src/router.rs
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/Cargo.lock

Bumps hashbrown, used via `ockam_core`

chore: upgrade hashbrown and remove redundant imports

---

implementations/rust/examples/worker/examples/worker_receive_match.rs
implementations/rust/ockam/ockam_node/src/context.rs

This PR adds a convenience function to the Context API that allows users to receive based on a conditional filter.

feat(rust): add receive_match to filter messages via conditional

---

implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/client.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/listener.ex
implementations/elixir/ockam/ockam/test/ockam/router_test.exs

FIX: add server ip/port to return route on TCP transport listener
FIX: route messages received from the connection on TCP transport client

fix[elixir]: reuse tcp connection when sending messages back

---

implementations/elixir/ockam/ockam/lib/ockam/node.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/client.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/listener.ex
implementations/elixir/ockam/ockam/test/ockam/router_test.exs

Move code for sending messages from tcp listener to tcp client
Establish connections by creating new clients as workers
Make clients add its own identity instead of ip/port to return route
This allows the ping-pong example when two workers on different machines can talk back and forth using the same connection.
Depends on #1074

feat[elixir]: register tcp client as worker to route back to it without reconnecting

---

implementations/rust/examples/node/Cargo.lock
implementations/rust/examples/worker/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_node/CHANGELOG.md
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/README.md
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock

- Routing APIs.
- Router registration.
- Message forwarding.
- Mechanism for stopping a single worker.
- The `receive_match` API allows workers to block until receivng a specific message type.
- Dependency updates.
- External router implementations don't need to accept TransportMessage, or parse specific user message types.
- Improved logging.

feat(rust): ockam_node v0.4.0

---

implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/CHANGELOG.md
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/README.md

- Route metadata wrapper type.
- New implementations of TCP Router and TCP Listener.
- Dependencies updated.
- Split TCP worker into two parts: sender & receiver.

feat(rust): ockam_transport_tcp v0.2.0

---

implementations/rust/ockam/ockam_transport_tcp/Cargo.toml

fix(rust): un-wildcard ockam dep for ockam_transport_tcp

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml

Bumping accidentally reverted version number for ockam crate

fix(rust): update reverted vers number in ockam toml

---

implementations/rust/examples/tcp/examples/network_echo_server.rs
implementations/rust/examples/tcp/examples/relay_echo_client.rs
implementations/rust/examples/tcp/examples/relay_echo_server.rs
implementations/rust/ockam/ockam_core/src/routing/address.rs
implementations/rust/ockam/ockam_core/src/routing/route.rs

This change splits the forwarding example up into two binaries that people can run.
The code currently assumes that https://github.com/ockam-network/ockam/commit/ad66ce8c1f4184f975c5c668209a86bfd3964c4f has been applied to the target hub implementation

Split forwarding example

---

documentation/guides/rust/01-workers/README.md
documentation/guides/rust/02-transports/README.md
documentation/guides/rust/03-hub/README.md
documentation/guides/rust/README.md
documentation/guides/rust/get-started/README.md

Restores markdown based links in guide

docs: markdown links in guide

---

README.md

- The Get Started section has a link to the rust guide but it's pointing it to https://github.com/ockam-network/ockam/blob/develop/%22documentation/guides/rust/README.md#rust-guide%22 which gives you a 404
- This is fixed by removing the quotes

docs: fix link to rust guide in README.md

---

implementations/elixir/ockam/ockam/.credo.exs
implementations/elixir/ockam/ockam_hub/.credo.exs
implementations/elixir/ockam/ockam_hub/lib/hub.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/alias.ex

Simplified version of the forwarder service: not trying to emulate a mailbox, just replaces an alias with a registered route.

feat(elixir): a simpler alias service for hub to forward messages

---

implementations/rust/ockam/ockam_core/src/message.rs

Rebase of https://github.com/ockam-network/ockam/pull/1151

chore(rust): rename route fields in transport message

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/CHANGELOG.md
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_core/README.md
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml

- Expose onward route information to user workers.
- Random address generation.
- Switch payload encoding from bincode to bare.
- Split forwarding examples into two binaries.
- Rename route fields in transport message.
- RemoteMailbox has been moved to the `ockam` crate.

ockam_core v0.7.0

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/CHANGELOG.md
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_core/README.md
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_node/CHANGELOG.md
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/README.md
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml

- Expose onward route information to user workers.
- Make context receive retry receiving if wrong type.
- Handle message payloads without inner length.
- Make consuming cancel wrapper yield routed wrapper
- Use special message parsing for context receive.
- Log worker errors instead of panicking.

ockam_node v0.5.0

---

implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/CHANGELOG.md
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/README.md
implementations/rust/ockam/ockam_key_exchange_x3dh/CHANGELOG.md
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/CHANGELOG.md
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/README.md
implementations/rust/ockam/ockam_vault/CHANGELOG.md
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.toml
implementations/rust/ockam/ockam_vault/README.md
implementations/rust/ockam/ockam_vault_core/CHANGELOG.md
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.toml
implementations/rust/ockam/ockam_vault_core/README.md

Updating ockam_core dependants: the key exchange crates and vault crates

feat(rust): update ockam_core dependants

---

implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_ffi/CHANGELOG.md
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_core/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.toml
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.toml
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml

Changes crate name to `ockam_ffi` instead of `ockam-ffi`

Move ockam-ffi crate to ockam_ffi

---

implementations/rust/ockam/ockam/CHANGELOG.md
implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml

fix: bump ockam vers to pick up new ockam_core

---

implementations/elixir/ockam/ockam_hub/lib/hub.ex
implementations/elixir/ockam/ockam_hub/lib/hub/telemetry_forwarder.ex

Azure seems to redirect public IP access to the internal networking.
We need to know the public IP so we can provide it to users.
This commit uses an external service to get it since asking Azure is surprisingly difficult.

chore: explicitly pass public ip in telemetry_forwarder

---

implementations/rust/ockam/ockam/src/remote_mailbox.rs
implementations/rust/ockam/ockam_channel/src/key_exchange/initiator.rs
implementations/rust/ockam/ockam_channel/src/key_exchange/responder.rs
implementations/rust/ockam/ockam_channel/src/secure_channel.rs
implementations/rust/ockam/ockam_core/src/routing/address.rs
implementations/rust/ockam/ockam_examples/example_projects/channel/src/client_worker.rs
implementations/rust/ockam/ockam_examples/example_projects/credentials/src/issuer.rs
implementations/rust/ockam/ockam_examples/example_projects/node/examples/create_ping_pong_node.rs
implementations/rust/ockam/ockam_examples/example_projects/worker/examples/worker_local_routing.rs
implementations/rust/ockam/ockam_examples/example_projects/worker/examples/worker_multi_address.rs
implementations/rust/ockam/ockam_examples/example_projects/worker/examples/worker_simple_router.rs
implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_transport_tcp/src/listener.rs
implementations/rust/ockam/ockam_transport_tcp/src/receiver.rs
implementations/rust/ockam/ockam_transport_tcp/src/router.rs
implementations/rust/ockam/ockam_transport_tcp/src/sender.rs

* primary_address -> address
* add aliases which returns all secondary addresses
This was my suggestion from the miro board.  But may we should discuss how users should have access to their secondary functions.

refactor(rust): rename context address functions

---

examples/rust/get_started/examples/08-routing-over-transport-many-hops-initiator.rs
examples/rust/get_started/examples/08-routing-over-transport-many-hops-middle.rs
examples/rust/get_started/examples/08-routing-over-transport-many-hops-responder.rs
implementations/rust/ockam/ockam_core/src/routing/address.rs
implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/router.rs
implementations/rust/ockam/ockam_transport_tcp/src/receiver.rs

To run the example:
1. cargo run --example 08-routing-over-transport-many-hops-responder
2. cargo run --example 08-routing-over-transport-many-hops-middle
3. cargo run --example 08-routing-over-transport-many-hops-initiator
To run this in a single binary the TcpTransport API needs to change slightly.

Getting tcp_transport working with multi-hop routes

---

examples/rust/get_started/examples/10-routing-to-hub.rs

Adds a `ctx.stop` to end of step 10, so it doesn't run forever. It's not a server, no need

docs(rust): step 10 add a stop for easier testing

---

implementations/rust/ockam/ockam/Cargo.lock
implementations/rust/ockam/ockam_channel/Cargo.lock
implementations/rust/ockam/ockam_core/Cargo.lock
implementations/rust/ockam/ockam_examples/Cargo.lock
implementations/rust/ockam/ockam_ffi/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_core/CHANGELOG.md
implementations/rust/ockam/ockam_key_exchange_core/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_x3dh/Cargo.lock
implementations/rust/ockam/ockam_key_exchange_xx/Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.lock
implementations/rust/ockam/ockam_transport_tcp/Cargo.lock
implementations/rust/ockam/ockam_vault/Cargo.lock
implementations/rust/ockam/ockam_vault_core/Cargo.lock
implementations/rust/ockam/ockam_vault_sync_core/Cargo.lock
implementations/rust/ockam/ockam_vault_test_suite/Cargo.lock
implementations/rust/ockam/signature_bbs_plus/Cargo.lock
implementations/rust/ockam/signature_bls/Cargo.lock
implementations/rust/ockam/signature_core/Cargo.lock
implementations/rust/ockam/signature_ps/Cargo.lock

Release ockam_key_exchange_core v0.3.1 .
Contains a cherry-picked commit from main, to resolve a conflict between the branches.

feat(rust): ockam_key_exchange_core v0.3.1

---

implementations/rust/ockam/ockam/src/credential.rs
implementations/rust/ockam/ockam/src/credential/issuer.rs
implementations/rust/ockam/ockam/src/credential/request.rs
implementations/rust/ockam/ockam/src/credential/verifier.rs
implementations/rust/ockam/ockam/src/error.rs
implementations/rust/ockam/ockam/src/lease.rs
implementations/rust/ockam/ockam/src/lib.rs
implementations/rust/ockam/ockam/src/remote_forwarder.rs

One of the serde dependencies precludes a crate-wide `missing_docs` attribute. That attribute was added on all sub-modules though.

Add the standard crate lib header to ockam crate

---

tools/docker/builder/Dockerfile

Upgrades Rust to 1.51 and adds some additional deps needed for `cargo audit`
Thanks @psinghal20 for finding the breakage!

ci: update docker builder to rust 1.51

---

implementations/c/ockam/codec/tests/endpoint_test.c

Rebase of https://github.com/ockam-network/ockam/pull/1454

fix(c): rename duplicated endpoint_buffer variable

---

implementations/rust/ockam/signature_ps/src/blind_signature.rs
implementations/rust/ockam/signature_ps/src/prover.rs

Fixes https://github.com/ockam-network/ockam/issues/1435 by changing `BYTES` from 96 to 128.

fix(rust): fix key size of ps key

---

implementations/elixir/ockam/ockam/lib/ockam/examples/stream/bi_directional/secure_channel.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/client/bi_directional.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/client/bi_directional/publisher_proxy.ex
implementations/elixir/ockam/ockam_hub/config/config.exs

Deduplication in the stream client is not reliable enough.
Since secure channel do not require deduplication, it's not critically needed

fix(elixir): remove deduplication from stream client

---

documentation/guides/rust/get-started/03-routing/README.md

`ctx.forward()` expects a `local_message`, but got `transport_message`

fix(rust): use local message in hop.rs

---

examples/rust/get_started/Cargo.toml

Fixed up commit from https://github.com/ockam-network/ockam/pull/1553

fix(rust): select a version for rand in the examples

---

examples/rust/get_started/Cargo.lock
examples/rust/get_started/examples/06-secure-channel-many-hops.rs
examples/rust/get_started/examples/09-secure-channel-over-many-transport-hops-initiator.rs
examples/rust/get_started/examples/09-secure-channel-over-many-transport-hops-responder.rs
examples/rust/get_started/examples/12-secure-channel-over-cloud-node-forwarding-initiator.rs
examples/rust/get_started/examples/12-secure-channel-over-cloud-node-forwarding-responder.rs
examples/rust/get_started/examples/13-secure-channel-with-entity.rs
implementations/rust/ockam/ockam_entity/examples/api.rs
implementations/rust/ockam/ockam_entity/src/authentication.rs
implementations/rust/ockam/ockam_entity/src/channel.rs
implementations/rust/ockam/ockam_entity/src/entity.rs
implementations/rust/ockam/ockam_entity/src/lib.rs
implementations/rust/ockam/ockam_entity/src/worker/entity_worker.rs
implementations/rust/ockam/ockam_entity/src/worker/request.rs

This inverts control of Vault construction, moving it outside of the entity lifecycle.
`Entity::create` now takes the address of a Vault. Examples and tests have been updated to create explicit software vaults to use with Entities.

feat(rust): inject vault into entity construction

---

.vscode/settings.json

Add rust-analyzer configuration to detect all crates.
This PR should enable us work from the root directory without using cargo workspace.

build(rust): add rust-analyzer configuration

---

examples/rust/get_started/examples/14-stream-over-cloud-node-initiator.rs
examples/rust/get_started/examples/14-stream-over-cloud-node-responder.rs
examples/rust/get_started/examples/15-secure-channel-over-stream-over-cloud-node-initiator.rs
examples/rust/get_started/examples/15-secure-channel-over-stream-over-cloud-node-responder.rs
implementations/rust/ockam/ockam/src/stream/consumer.rs
implementations/rust/ockam/ockam/src/stream/mod.rs
implementations/rust/ockam/ockam/src/stream/producer.rs

* rename tx, rx to sender, receiver
* rename some variables to match their types in order to increase code clarity
* match struct layout order to constructor argument order for better readability
* modify default stream polling interval to a more reasonable value (250 ms)
* remove default stream interval override in examples

chore(rust): refactor streams code for clarity & ergonomics

---

implementations/elixir/ockam/ockam_hub/config/runtime.exs
implementations/elixir/ockam/ockam_hub/lib/hub.ex
implementations/elixir/ockam/ockam_hub/lib/hub/telemetry_forwarder.ex

Node IP is used by TelemetryForwarder, which is a left over from
the previous integraiton with the Hub Console.
Remove IP resolution and default host from the config.
Disable TelemetryForwarder.

fix(elixir): cleanup config to disable node ip resolution on start

---

documentation/guides/draft/use-cases/end-to-end-encryption-with-kafka/README.md
examples/rust/ockam_kafka/examples/alice.rs
examples/rust/ockam_kafka/examples/bob.rs

- Adds  example code to the single page guide for kafka
- First draft integrating parts of the single page rust dev guide's README

docs: add example code to the single page guide for kafka

---

implementations/elixir/ockam/ockam/lib/ockam/worker.ex
implementations/elixir/ockam/ockam_hub/lib/hub.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/kafka.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/routing.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/stream.ex
implementations/elixir/ockam/ockam_hub/lib/hub/web/handlers/kafka_stream_handler.ex

Ockam.Node supervisor restarts all workers on max_restarts, this will
stop the service workers and not restart them because they're started
dynamically on hub start.
Move services and transports to the Hub supervisor so they are
restarted separately from dynamic workers.
This should improve availability of Hub services in case of failures.

feat(elixir): make hub services supervised by hub root supervisor

---

implementations/elixir/ockam/ockam/lib/ockam/stream/index/service.ex
implementations/elixir/ockam/ockam/lib/ockam/stream/index/shard.ex
implementations/elixir/ockam/ockam_hub/config/runtime.exs
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/stream.ex

Since index service is global in the hub, using some index management
integrations like kafka offset management can create a bottleneck for
all clients using the service.
Create a separate processes to perform the storage operations and only wait
for response if one required by the protocol.
TODO: further improvement would be to send the get response from the shard
as well avoiding any blocking on the service side.

feat(elixir): sharded access to stream index storage

---

implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/kafka.ex

fix(elixir): update module name to start stream_kafka_index service

---

implementations/rust/ockam/ockam_node_no_std/CHANGELOG.md
implementations/rust/ockam/ockam_node_no_std/Cargo.lock
implementations/rust/ockam/ockam_node_no_std/Cargo.toml
implementations/rust/ockam/ockam_node_no_std/src/lib.rs

Initial publish of the  `ockam_node_no_std` crate.

feat(rust): initial publish of ockam_node_no_std

---

implementations/elixir/ockam/ockam/lib/ockam/examples/stream/bi_directional/local.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/bi_directional/secure_channel.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/index_api.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/stream.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/stream_api.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/transport/printer.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/transport/tcp.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/transport/udp.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/address.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/handler.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/listener.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/udp.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/udp/address.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/udp/listener.ex
implementations/elixir/ockam/ockam/test/ockam/router_test.exs
implementations/elixir/ockam/ockam/test/ockam/transport/udp_test.exs
implementations/elixir/ockam/ockam_hub/lib/hub.ex

Separate tcp transport from tcp listener
Make tcp listener a gen server instead of a worker
Change the transport start API to make send enabled by default, but listener optional
TCP transport usage:
To create a listening transport:
```
Ockam.Transport.TCP.start(listen: [port: 4000])
```
To create a client-only transport:
```
Ockam.Transport.TCP.start()
```
Listening transport always supports client connections:
```
>> Ockam.Transport.TCP.start(listen: [port: 4000])
>> Ockam.Node.register_address("me", self())
>> Ockam.Router.route(%{onward_route: [Ockam.Transport.TCPAddress.new("localhost", 4000), "me"], return_route: [], payload: "HI"})
>> flush()
%{
onward_route: ["me"],
payload: "HI",
return_route: ["c5bf5d5c23a6e238"],
version: 1
}
```
Non-listening transport does not require port …

refactor(elixir): make tcp transport listener optional, simplify udp transport API

---

implementations/rust/ockam/ockam_transport_tcp/tests/send_receive.rs

- test: add basic tcp transport integration test
- test: use different contexts for listener and sender

test: add basic tcp transport integration test (rebase)

---

commitlint.config.js

When merging an external contribution, I missed fix up of 2 commit messages that do not pass lint.

ci: ignore lint for 2 more commits with upper case

---

documentation/use-cases/run-ockam-on-riscv/README.md

Previous PR didn't have the README attached

docs: add missing content for riscv

---

implementations/elixir/build.gradle
implementations/elixir/ockam/ockam/config/config.exs
implementations/elixir/ockam/ockam/lib/ockam/asymmetric_worker.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/messaging/delivery.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/messaging/filter.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/messaging/reliable_deduplication.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/messaging/shuffle.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/stream/bi_directional/secure_channel.ex
implementations/elixir/ockam/ockam/lib/ockam/messaging/confirm_pipe/receiver.ex
implementations/elixir/ockam/ockam/lib/ockam/messaging/confirm_pipe/wrapper.ex
implementations/elixir/ockam/ockam/lib/ockam/messaging/delivery/resend_pipe.ex
implementations/elixir/ockam/ockam/lib/ockam/messaging/index_pipe/sender.ex
implementations/elixir/ockam/ockam/lib/ockam/messaging/index_pipe/wrapper.ex
implementations/elixir/ockam/ockam/lib/ockam/messaging/ordering/monotonic/index_pipe.ex
implementations/elixir/ockam/ockam/lib/ockam/messaging/ordering/strict/confirm_pipe.ex
implementations/elixir/ockam/ockam/lib/ockam/messaging/ordering/strict/index_pipe.ex
implementations/elixir/ockam/ockam/lib/ockam/messaging/pipe_channel.ex
implementations/elixir/ockam/ockam/lib/ockam/pub_sub_subscriber.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/recoverable_client.ex
implementations/elixir/ockam/ockam/lib/ockam/worker.ex
implementations/elixir/ockam/ockam/test/ockam/helpers/filter.ex
implementations/elixir/ockam/ockam/test/ockam/messaging/delivery_test.exs
implementations/elixir/ockam/ockam_hub/config/runtime.exs
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/routing.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/pub_sub.ex

Currently messaging pipelines rely on the underlying protocols for message delivery guarantees (e.g. TCP).
Those intermediate workers or transports may or may not implement reliable delivery.
Resend pipe is implementing confirms and resends in order to ensure end-to-end reliable delivery
Please see `implementations/elixir/ockam/ockam/test/ockam/messaging/delivery_test.exs` for example usage

feat(elixir): resend pipe prototype for reliable delivery

---

implementations/rust/ockam/ockam_node_test_attribute/tests/trybuild.rs

https://github.com/ockam-network/ockam/pull/2156 changed this test harness to execute under the  `#[cfg(feature = "std")]` macro. `cargo test` by default does not execute the tests under this block, so the variable is then unused.
This change moves the variable instantiation to the same code block. This will only instantiate the variable then when it is needed for this block upon execution. In the future, if this behavior is no longer wanted, the instantiation of `trybuild::TestCases` can be moved.
Closes  #2188

fix(rust): fix unused variable warning in ockam_node_test_attribute

---

implementations/elixir/ockam/ockam_hub/config/runtime.exs
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/routing.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/tracing.ex
implementations/elixir/ockam/ockam_hub/test/hub/service/tracing_test.exs

Add a new service to trace messages going through the Hub.
A tracing address is registered same way as forwarding address
Registered tracing address worker copies payloads to the registered route

feat(elixir): add tracing service to trace payloads

---

implementations/rust/ockam/ockam_transport_websocket/src/lib.rs

chore(rust): change WebSocket address type constant from 2 to 3.
As per issue #2194.

chore(rust): change WebSocket address type constant from 2 to 3

---

implementations/rust/ockam/ockam_core/Cargo.toml
implementations/rust/ockam/ockam_core/src/lib.rs
implementations/rust/ockam/ockam_executor/src/executor.rs
implementations/rust/ockam/ockam_executor/src/lib.rs
implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/messages.rs
implementations/rust/ockam/ockam_node/src/relay/processor_relay.rs
implementations/rust/ockam/ockam_node/src/relay/worker_relay.rs
implementations/rust/ockam/ockam_node/src/router/record.rs
implementations/rust/ockam/ockam_node/src/router/shutdown.rs

This PR fixes various things that are currently breaking `no_std` builds:
* `ockam_executor` deadlocks inside the `ProcessorRelay` run loop.
* `ockam_executor` is missing an implementation of the `warn!` logging macro
* we don't (yet) have an implementation of `select!` for `ockam_executor`
* adding `futures-util` with default features enabled breaks `no_std` builds
```
cd implementations/rust/ockam/ockam
cargo build --no-default-features --features "no_std alloc software_vault"
```
For bonus points arm cortex-m builds can be tested with:
```
cargo +nightly build --target thumbv7em-none-eabihf --no-default-features --features "no_std alloc software_vault"
```

fix(rust): fix no_std builds

---

Cargo.lock

This contains the fix from https://rustsec.org/advisories/RUSTSEC-2021-0124.

chore(rust): run `cargo update` to get the fix from tokio 1.13.0

---

.github/workflows/cargo_update_check.yml
.github/workflows/ockam_features_check.yml
implementations/rust/ockam/ockam/src/lib.rs
implementations/rust/ockam/ockam_channel/src/lib.rs
implementations/rust/ockam/ockam_core/src/lib.rs
implementations/rust/ockam/ockam_entity/src/lib.rs
implementations/rust/ockam/ockam_executor/src/channel.rs
implementations/rust/ockam/ockam_executor/src/executor.rs
implementations/rust/ockam/ockam_executor/src/lib.rs
implementations/rust/ockam/ockam_executor/src/oneshot.rs
implementations/rust/ockam/ockam_executor/src/runtime.rs
implementations/rust/ockam/ockam_ffi/src/lib.rs
implementations/rust/ockam/ockam_key_exchange_core/src/lib.rs
implementations/rust/ockam/ockam_key_exchange_xx/src/lib.rs
implementations/rust/ockam/ockam_node/src/lib.rs
implementations/rust/ockam/ockam_node_attribute/src/lib.rs
implementations/rust/ockam/ockam_node_test_attribute/src/lib.rs
implementations/rust/ockam/ockam_transport_tcp/src/lib.rs
implementations/rust/ockam/ockam_transport_websocket/src/lib.rs
implementations/rust/ockam/ockam_vault/src/lib.rs
implementations/rust/ockam/ockam_vault_core/src/lib.rs
implementations/rust/ockam/ockam_vault_sync_core/src/lib.rs
implementations/rust/ockam/signature_bbs_plus/src/lib.rs
implementations/rust/ockam/signature_bls/src/lib.rs
implementations/rust/ockam/signature_bls/src/secret_key.rs
implementations/rust/ockam/signature_core/src/lib.rs
implementations/rust/ockam/signature_ps/src/lib.rs

Right now in the rust code, if there's a compiler warning during local development, the build will fail to complete. This is inconvenient, since *really*, we only care about this stuff when *landing* code in the repo. As a result, this PR moves these checks entirely into CI (where they already existed, for the most part, although I firmed that up).
The exception to this the `unsafe_code` lint, which is reported by various tooling, and isn't *really* in the same category as other lints. This one is kept as deny in the crates that can use it (although perhaps it should be increased to `#![forbid]` in the future).

chore(rust): deny warnings in ci, not local development

---

Cargo.lock
implementations/rust/ockam/ockam_channel/src/lib.rs
implementations/rust/ockam/ockam_command/Cargo.toml
implementations/rust/ockam/ockam_command/src/bin/ockam.rs
implementations/rust/ockam/ockam_command/src/config.rs
implementations/rust/ockam/ockam_command/src/console.rs
implementations/rust/ockam/ockam_entity/src/authentication.rs
implementations/rust/ockam/ockam_entity/src/channel.rs
implementations/rust/ockam/ockam_entity/src/identifiers.rs
implementations/rust/ockam/ockam_entity/src/lib.rs
implementations/rust/ockam/ockam_key_exchange_x3dh/src/lib.rs
implementations/rust/ockam/ockam_key_exchange_xx/src/lib.rs
implementations/rust/ockam/ockam_node_attribute/src/lib.rs
implementations/rust/ockam/ockam_node_test_attribute/src/hygiene.rs
implementations/rust/ockam/ockam_vault_test_attribute/src/lib.rs
implementations/rust/ockam/signature_bls/src/partial_signature.rs
implementations/rust/ockam/signature_bls/src/partial_signature_vt.rs
implementations/rust/ockam/signature_bls/src/secret_key_share.rs
implementations/rust/ockam/signature_ps/src/lib.rs
tools/docs/example_blocks/src/main.rs
tools/docs/example_runner/src/main.rs
tools/ockam-hub-cli/src/auth/github.rs

1. Fixes `cargo fmt` errors and other fallout from #2242.
2. Fixes  #2241 (`gradlew lint` on rust code now passes).
3. Fixes (or `#[allows]` where reasonable) every clippy error in the workspace.

Fix all the linting problems

---

implementations/rust/build.gradle

By not generating documentation for dependencies. Ideally we'd use `RUSTDOCFLAGS="--check"` but it isn't stable yet, and I don't know how much more it would speed things up.
Times, according to gradle:
Before (already built): `9m 2s`
Before (full rebuild): I don't know, presumably longer.
After (already built): `2m 23s`
After (full rebuild): `5m 1s`

chore(rust): improve performance of gradle lint task

---

implementations/rust/ockam/ockam_vault/src/xeddsa.rs

When I try to compile the following example for Ockam embedded:
[examples/04-routing-over-transport-responder.rs](https://github.com/antoinevg/hello_ockam_embedded/blob/8ecb206bbe71660c386bdf53ab666156454ca55f/examples/04-routing-over-transport-responder.rs) 
I get the following build error:
```
cargo +nightly -Z unstable-options \
--config "target.cfg.runner = 'arm-none-eabi-gdb -q -x openocd-itm.gdb'" \
build --example 04-routing-over-transport-responder \
--target thumbv7em-none-eabihf \
--no-default-features \
--features="stm32h7,bsp_nucleo_h7xx,no_main"
Compiling hello-ockam v0.1.0 (/Users/antoine/Ockam/hello_ockam_embedded.git)
Compiling ockam_vault v0.34.0 (/Users/antoine/Ockam/ockam.git/implementations/rust/ockam/ockam_vault)
error[E0599]: no function or associated item named …
```

fix(rust): import correct ed25519 signature trait

---

tools/gradle/wrapper/gradle-wrapper.properties

On newer JDK versions (`>= openjdk16`)  all gradle operations  fail with the message:
```
Could not open settings generic class cache for settings file ...
```
Updating gradle to the latest version (`7.3.1`) resolves this issue.

build: bump gradle version to 7.3.1

---

implementations/elixir/ockam/ockam/lib/ockam/router.ex
implementations/elixir/ockam/ockam/lib/ockam/router/message_handler.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/client.ex
implementations/elixir/ockam/ockam/lib/ockam/transport/tcp/handler.ex

Load balancers tend to stop connections when they idle for few minutes.
TCP keepalives may be used to address that, but keepalive interval requires
kernel tuning.
TCP transport can support custom keepalive heartbeats by sending periodic empty
messages from TCP client to handler.
Handler ignores empty messages.
Client can be configured to send heartbeats every `interval` milliseconds
by using `heartbeat: interval` option.
To make sure client is created with `heartbeat` option,
TCP transport should be started with client options:
`Ockam.Transport.TCP.start(client_options: [heartbeat: interval])`

feat(elixir): support heartbeats in TCP transport

---

.github/workflows/commitlint.yml
.github/workflows/editorconfig.yml

Editorconfig and commit message linter is run twice on a pull request as a pull request perform a `on: push and pull_request`. 
We should only run the workflow if it's a pull request or if merged to develop.

ci: reduce commitlint and editorconfig run

---

.github/workflows/ockam_features_check.yml

Cargo feature check should only run if there are changes to our rust
crates or if merged to develop

ci: reduce cargo feature check run

---

tools/scripts/release/crate-bump.sh

The script uses `-p` instead of `--package` which is not recognized as a `cargo-release` argument.
Additionally, `echo y` does not work to avoid confirmation. The proper way to do that is `--no-confirm`

ci: fix invalid argument for cargo release

---

implementations/elixir/ockam/ockam/test/ockam/messaging/ordering_test.exs

There is an unstable test https://github.com/ockam-network/ockam/runs/4458049139?check_suite_focus=true
Increased the timeout waiting for ordered messages

test(elixir): increase timeout in ordering test to make it more stable

---

implementations/rust/ockam/ockam/src/channel/listener.rs
implementations/rust/ockam/ockam/src/channel/mod.rs
implementations/rust/ockam/ockam/src/channel/tests.rs
implementations/rust/ockam/ockam/src/channel/worker.rs
implementations/rust/ockam/ockam/src/lib.rs
implementations/rust/ockam/ockam/src/pipe/behavior/handshake.rs
implementations/rust/ockam/ockam/src/pipe/behavior/mod.rs
implementations/rust/ockam/ockam/src/pipe/behavior/resend.rs
implementations/rust/ockam/ockam/src/pipe/listener.rs
implementations/rust/ockam/ockam/src/pipe/mod.rs
implementations/rust/ockam/ockam/src/pipe/receiver.rs
implementations/rust/ockam/ockam/src/pipe/sender.rs
implementations/rust/ockam/ockam/src/pipe/tests.rs
implementations/rust/ockam/ockam/src/protocols/channel/mod.rs
implementations/rust/ockam/ockam/src/protocols/mod.rs
implementations/rust/ockam/ockam/src/protocols/pipe/internal.rs
implementations/rust/ockam/ockam_core/src/routing/route.rs

The initial implementation of bi-directional messaging channels, built on top of uni-directional messaging pipes.
During the handshake creation two pipe workers are spawned on each end of the channel (Sender and Receiver), plus an additional channel worker that is responsible for doing route backtracing.
Currently this code does not allow for additional behaviour to be attached to a channel worker (for example to implement secure channels)

Rust bi-directional messaging channels

---

implementations/rust/ockam/ockam_entity/src/contact.rs

docs: remove stale ref to `KeyAttributes`

---

.github/dependabot.yml

package-ecosystem value must be npm even though we use yarn.

ci: fix dependabot coniguration for typescript

---

.github/workflows/all.yml
.github/workflows/commitlint.yml
.github/workflows/editorconfig.yml
.github/workflows/elixir.yml
.github/workflows/gradle.yml
.github/workflows/rust.yml

Use Concurrency Groups to cancel github workflows if there is a new trigger.

ci: cancel github workflows if there is a new trigger

---

implementations/rust/ockam/ockam_macros/src/node_attribute/parser.rs

fix(rust): fix no_std compilation error due to `ockam::node` attribute

---

.github/workflows/all.yml
.github/workflows/commitlint.yml
.github/workflows/editorconfig.yml
.github/workflows/elixir.yml
.github/workflows/gradle.yml
.github/workflows/rust.yml

Some github UIs, like the gh command don't show workflow name
when showing running checks. This repition makes it easier to
observe what is running.

ci: prefix workflow names to job names

---

.devcontainer/Dockerfile
.github/actions/cargo_home_cache/action.yml
.github/actions/cargo_target_dir_cache/action.yml
.github/actions/cargo_target_dir_pre_cache/action.yml
.github/actions/elixir_cache/action.yml
.github/actions/gradle_cache/action.yml
.github/workflows/all.yml
.github/workflows/documentation.yml
.github/workflows/elixir.yml
.github/workflows/rust.yml
examples/rust/ockam_kafka/Dockerfile
examples/rust/tcp_inlet_and_outlet/Dockerfile
tools/docker/builder/Dockerfile

Prior to saving the cache, delete artifacts which cannot be meaningfully
cached from the target folder. Specifically: all of the builds of our own crates.

ci: remove built workspace members before caching

---

implementations/rust/ockam/ockam_entity/src/lease/json_proto.rs

Documents the prototypical JSON client for Ockam Cloud TokenLeaseManager service

docs(rust): document `JSON` `TokenLeaseManager` client

---

implementations/elixir/ockam/ockam/lib/ockam/messaging/pipe_channel/responder.ex
implementations/elixir/ockam/ockam/lib/ockam/pub_sub_subscriber.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/pub_sub.ex

Currently pub_sub_service will create a topic worker without replying to the caller
Add a reply in format of: `"name:topic"` (same as subscription call) from the topic worker address, which allows the subscribing client to use the return route to see address of the pubsub topic worker. Similarly to the forwarding workers reply.

feat(elixir): make pub_sub service reply after subscription

---

implementations/elixir/ockam/ockam_hub/lib/hub/service/forwarding.ex
implementations/elixir/ockam/ockam_hub/test/hub/service/forwarding_test.exs

Currently forwarding service forwarders send messages to the registered worker without additional onward route after that.
This makes it not possible to add more onward route after the registered worker.
If worker route `[forward_to]` is registered in `forwarder`
Then message sent to `[forwarder, something_else]` 
Will be sent to `[forward_to]`
`something_else` is lost
Add the onward route from messages on forwarding service forwarders to the forwarded message
If worker route `[forward_to]` is registered in `forwarder`
Then message sent to `[forwarder, something_else]` 
Will be sent to `[forward_to, something_else]`

fix(elixir): propagate onward route in message forwarded by forwarding service

---

Cargo.lock
implementations/rust/ockam/ockam_transport_ble/Cargo.toml
implementations/rust/ockam/ockam_transport_ble/README.md
implementations/rust/ockam/ockam_transport_ble/examples/04-routing-over-ble-transport-initiator.rs
implementations/rust/ockam/ockam_transport_ble/examples/05-secure-channel-over-ble-transport-initiator.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/bluetooth_hci/ble_uart.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/bluetooth_hci/mod.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/btleplug/mod.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/mod.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/mutex.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/packet.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/stream.rs
implementations/rust/ockam/ockam_transport_ble/src/error.rs
implementations/rust/ockam/ockam_transport_ble/src/lib.rs
implementations/rust/ockam/ockam_transport_ble/src/macros.rs
implementations/rust/ockam/ockam_transport_ble/src/router/handle.rs
implementations/rust/ockam/ockam_transport_ble/src/router/mod.rs
implementations/rust/ockam/ockam_transport_ble/src/transport.rs
implementations/rust/ockam/ockam_transport_ble/src/types.rs
implementations/rust/ockam/ockam_transport_ble/src/workers/listener.rs
implementations/rust/ockam/ockam_transport_ble/src/workers/mod.rs
implementations/rust/ockam/ockam_transport_ble/src/workers/receiver.rs
implementations/rust/ockam/ockam_transport_ble/src/workers/sender.rs

* A new crate adding  Bluetooth Low Energy support to Ockam
* BLE Client support on Linux, macOS, Windows
* BLE Server support on `atsame54`, `nucleo_h7xx`
* Support for STMicroElectronics bluenrg radios

feat(rust): initial commit for ockam_transport_ble crate

---

implementations/rust/ockam/ockam_transport_ble/Cargo.toml

This is blocking release of about half of the crates 😓

chore(rust): fixup `ockam_transport_ble` for publish (missing crate version)

---

deny.toml
implementations/rust/build.gradle

- Ignore `RUSTSEC-2020-0159` advisory till fixed #2541 
- Ignore `RUSTSEC-2022-0008` advisory till fixed #2540
- Cargo deny now checks for all features in CI

ignore `RUSTSEC-2020-0159` advisory

---

tools/scripts/release/README.md
tools/scripts/release/changelog.sh
tools/scripts/release/crate-bump.sh
tools/scripts/release/crates-to-publish.sh
tools/scripts/release/tagging.sh

This PR fixes an issue where we don't release/bump crates whose inter-dependency is bumped.

release script update

---

implementations/elixir/ockam/ockam/lib/ockam/node/registry.ex
implementations/elixir/ockam/ockam/lib/ockam/worker.ex
implementations/elixir/ockam/ockam_hub/lib/hub/telemetry_poller.ex
implementations/elixir/ockam/ockam_hub/test/hub/service/forwarding_test.exs

Registry adds options instead of addresses in worker
Make sure only extra addresses are added to registry

fix(elixir): fix extra address reporting via registry service

---

implementations/rust/ockam/ockam/tests/node/std/pass_with_imported_context.rs
implementations/rust/ockam/ockam_macros/src/node_attribute.rs

It also modifies tests to correctly catch this error.

fix(rust) - node macro - imports ockam context as used in the input function

---

tools/docs/example_runner/get_started.ron
tools/docs/example_runner/kafka.ron
tools/docs/example_runner/src/main.rs
tools/docs/example_runner/tcp_inlet_and_outlet.ron
tools/docs/run_examples.sh
tools/docs/run_kafka_example.sh

The script ockam/tools/docs/run_examples.sh tests some example code but does not run tests on ockam/examples/rust/tcp_inlet_and_outlet.
Add tests so that tcp_inlet_and_outlet code is tested. This is related to #2256. This requires updating the shell script (run_examples.sh), the test runner (example_runner), and the scripts read by the test runner (*.ron).
Some notes...
- It appears the Docker image does not include python3, so, just in case, these new tests use ockam.io:80 as a HTTP endpoint when testing (instead of launching a local python3 HTTP server, as Ockam guides suggest).
- The test harness will now stop as soon as a test fails and will exit with a non-0 code.
- A test (aka stage) will fail if a spawned process exits with an error, or if a 'match' attempt times out (currently 120 …

test(rust): add test for examples/rust/tcp_inlet_and_outlet

---

Cargo.lock
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam/src/system/handler.rs

Seems to break `no_std` and isn't really needed anyway.

chore(rust): remove the `dyn-clonable` dependency

---

Cargo.lock
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/src/parser.rs
implementations/rust/ockam/ockam_node/src/tests.rs

Inside parser::message(), when serde_bare::from_slice() fails to decode a payload we prepend the length of the payload to the payload and try again.
The length is prepended as an unsigned byte (u8). That does not match the BARE spec but works for payloads below 127 bytes.
Use serde_bare to prepend the length as a BARE Uint data type.
Add a test for parser::message() that fails with the old code and passes with the new. 
Fixes #2236

fix(rust): use serde_bare to prepend length to payload when missing

---

.github/workflows/rust.yml
implementations/rust/ockam/ockam/tests/main.rs

Closes #2639 
Because it includes it.
This has a long comment explaining the motivation.

Only test macro error output against the stable version of rust (rather than both stable and nightly)

---

implementations/rust/ockam/ockam_command/src/cmd/inlet.rs
implementations/rust/ockam/ockam_command/src/session/initiator.rs
implementations/rust/ockam/ockam_command/src/session/msg.rs
implementations/rust/ockam/ockam_command/src/session/responder.rs

Requesed by @mrinalwadhwa -- only logical change is that I noticed we retry immediately on failure to start session. I added a small sleep, so that we don't behave badly in unexpected cases (we don't want to spam logs, saturate the network, etc).

chore(rust): improve logging of ockam_command's session keep-alive code

---

implementations/elixir/ockam/ockam_hub/config/config.exs
implementations/elixir/ockam/ockam_hub/lib/hub/log_formatter.ex

Elixir logs can have line breaks which does not work too well with log export and processing
Replace line breaks in log messages with `\n`

fix(elixir): remove newlines from log messages

---

examples/elixir/get_started/07-routing-via-remote-forwarder-responder.exs
examples/elixir/get_started/08-secure-channel-over-remote-forwarder-responder.ex
examples/elixir/tcp_inlet_and_outlet/04-outlet.exs
examples/rust/get_started/examples/old/10-routing-to-a-cloud-node.rs
implementations/elixir/ockam/ockam/lib/ockam/examples/forwarding/forwarding.ex
implementations/elixir/ockam/ockam/lib/ockam/examples/messaging/reliable_deduplication.ex
implementations/elixir/ockam/ockam/lib/ockam/workers/pub_sub_subscriber.ex
implementations/elixir/ockam/ockam_hub/docs/token-lease-manager.md
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/discovery.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/routing.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/secure_channel.ex
implementations/elixir/ockam/ockam_hub/lib/hub/service/provider/token_lease_manager.ex
implementations/elixir/ockam/ockam_hub/test/hub/service/tracing_test.exs

Currently we have inconsistency in service worker addresses, some have a `_service` suffix, some don't.
Remove `_service` suffix for services
Keep backwards compatible `forwarding_service` and `static_forwarding_service` for RemoteForwarder
In RemoteForwarder in Rust code: change service addresses to `forwarding` and `static_forwarding`

chore: remove _service suffix from service addresses

---

implementations/rust/ockam/ockam_transport_tcp/src/portal/portal_receiver.rs

This is an alternative to #2707, which keeps the overall structure and only reduces the buffer size back to the old (pre #2702) value. Unlike #2707, I haven't actually checked if this one works.
(That said, if it *doesn't* work, then that tells us something else that patch is broken, which would be surprising...)

fix(rust): reduce `MAX_PAYLOAD_SIZE` back to 256

---

Cargo.lock
implementations/rust/ockam/ockam/CHANGELOG.md
implementations/rust/ockam/ockam/Cargo.toml
implementations/rust/ockam/ockam/README.md
implementations/rust/ockam/ockam_command/CHANGELOG.md
implementations/rust/ockam/ockam_command/Cargo.toml
implementations/rust/ockam/ockam_transport_ble/CHANGELOG.md
implementations/rust/ockam/ockam_transport_ble/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/CHANGELOG.md
implementations/rust/ockam/ockam_transport_tcp/Cargo.toml
implementations/rust/ockam/ockam_transport_tcp/README.md

This fix is intended to address the hangs caused by the TCP buffer size issues.
Ideally this would be a patch release, but this part of the script's functionality doesn't seem to actually work, so it's a minor release.

Cut release v0.56.0

---

.github/workflows/rust.yml
implementations/rust/ockam/ockam_node/src/context.rs
implementations/rust/ockam/ockam_node/src/messages.rs
implementations/rust/ockam/ockam_node/src/parser.rs
implementations/rust/ockam/ockam_node/src/relay/processor_relay.rs
implementations/rust/ockam/ockam_node/src/router/mod.rs
implementations/rust/ockam/ockam_node/src/router/record.rs
implementations/rust/ockam/ockam_transport_tcp/src/portal/portal_receiver.rs
implementations/rust/ockam/ockam_transport_tcp/src/workers/receiver.rs

This finishes up #2706 by fixing clippy issues and disabling the no_std check in CI.

fix(rust): fix `ProcessorRelay`

---

Cargo.lock
implementations/rust/ockam/ockam_transport_ble/Cargo.toml
implementations/rust/ockam/ockam_transport_ble/examples/04-routing-over-ble-transport-initiator.rs
implementations/rust/ockam/ockam_transport_ble/examples/05-secure-channel-over-ble-transport-initiator.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/bluetooth_hci/mod.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/btleplug/mod.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/mod.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/packet.rs
implementations/rust/ockam/ockam_transport_ble/src/driver/stream.rs
implementations/rust/ockam/ockam_transport_ble/src/router/mod.rs
implementations/rust/ockam/ockam_transport_ble/src/transport.rs
implementations/rust/ockam/ockam_transport_ble/src/types.rs
implementations/rust/ockam/ockam_transport_ble/src/workers/sender.rs

This pull request removes the following dependencies from the `ockam_transport_ble` crate:
* `ockam`
* `ockam_executor`

chore(rust): clean ockam transport ble dependencies

---

.editorconfig
documentation/architecture/messaging/Accessibility.md
documentation/architecture/messaging/Delivery.md
documentation/architecture/messaging/Errors.md
documentation/architecture/messaging/Ordering.md
documentation/architecture/messaging/Pipes_Channels.md
documentation/architecture/messaging/Pipes_Directory.md
documentation/architecture/messaging/README.md
documentation/architecture/messaging/Reliability.md
documentation/architecture/messaging/Routing.md
documentation/architecture/messaging/Sessions.md

This PR includes a bunch of typo fixes as well as some rephrasings of some sentences that seemed confusing to me.
The [first commit](https://github.com/ockam-network/ockam/pull/2660/commits/74c021f8fd87fb0cb8e4ed5e0caa5c902c8c4dd3) includes the fixes, the second commit applies the formatting, so I'd recommend checking the first commit in isolation to see the fixes more clearly.

chore(docs): review messaging docs

---

deny.toml
implementations/rust/build.gradle

Remove cargo deny installation from CI
Remove RUSTSEC-2022-0008 ignore from deny config closes https://github.com/ockam-network/ockam/issues/2540

remove cargo deny installation in `CI`

---

Cargo.lock
implementations/rust/ockam/ockam_command/Cargo.toml
implementations/rust/ockam/ockam_command/src/lib.rs
implementations/rust/ockam/ockam_node/Cargo.toml
implementations/rust/ockam/ockam_node/src/node.rs

I had thought this was already done, but maybe it got lost in one of the rebases.

fix(rust): enable `SpanTrace` capture during tracing registration
